/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BlogArticle } from '../../models/blog-article';

export interface GetExternalCmsArticle$Params {
  slug: string;
}

export function getExternalCmsArticle(http: HttpClient, rootUrl: string, params: GetExternalCmsArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<BlogArticle>> {
  const rb = new RequestBuilder(rootUrl, getExternalCmsArticle.PATH, 'get');
  if (params) {
    rb.path('slug', params.slug, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BlogArticle>;
    })
  );
}

getExternalCmsArticle.PATH = '/api/external/cms/articles/{slug}';
