/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { AccessResponse } from '../models/access-response';
import { AdminBootstrapStatus } from '../models/admin-bootstrap-status';
import { beginMfaEnrollment } from '../fn/framework/begin-mfa-enrollment';
import { BeginMfaEnrollment$Params } from '../fn/framework/begin-mfa-enrollment';
import { completeMfa } from '../fn/framework/complete-mfa';
import { CompleteMfa$Params } from '../fn/framework/complete-mfa';
import { completePasskeyMfa } from '../fn/framework/complete-passkey-mfa';
import { CompletePasskeyMfa$Params } from '../fn/framework/complete-passkey-mfa';
import { confirmEmail } from '../fn/framework/confirm-email';
import { ConfirmEmail$Params } from '../fn/framework/confirm-email';
import { confirmMfaEnrollment } from '../fn/framework/confirm-mfa-enrollment';
import { ConfirmMfaEnrollment$Params } from '../fn/framework/confirm-mfa-enrollment';
import { createBootstrapAdministrator } from '../fn/framework/create-bootstrap-administrator';
import { CreateBootstrapAdministrator$Params } from '../fn/framework/create-bootstrap-administrator';
import { createUser } from '../fn/framework/create-user';
import { CreateUser$Params } from '../fn/framework/create-user';
import { DeliverySummary } from '../models/delivery-summary';
import { disableMfa } from '../fn/framework/disable-mfa';
import { DisableMfa$Params } from '../fn/framework/disable-mfa';
import { EmailMfaChallengeResponse } from '../models/email-mfa-challenge-response';
import { forgotPassword } from '../fn/framework/forgot-password';
import { ForgotPassword$Params } from '../fn/framework/forgot-password';
import { getAdminBootstrapStatus } from '../fn/framework/get-admin-bootstrap-status';
import { GetAdminBootstrapStatus$Params } from '../fn/framework/get-admin-bootstrap-status';
import { getCsrfToken } from '../fn/framework/get-csrf-token';
import { GetCsrfToken$Params } from '../fn/framework/get-csrf-token';
import { getDeliveryOperations } from '../fn/framework/get-delivery-operations';
import { GetDeliveryOperations$Params } from '../fn/framework/get-delivery-operations';
import { getFeatures } from '../fn/framework/get-features';
import { GetFeatures$Params } from '../fn/framework/get-features';
import { getProfile } from '../fn/framework/get-profile';
import { GetProfile$Params } from '../fn/framework/get-profile';
import { getRegistrationSettings } from '../fn/framework/get-registration-settings';
import { GetRegistrationSettings$Params } from '../fn/framework/get-registration-settings';
import { getSecuritySettings } from '../fn/framework/get-security-settings';
import { GetSecuritySettings$Params } from '../fn/framework/get-security-settings';
import { listSessions } from '../fn/framework/list-sessions';
import { ListSessions$Params } from '../fn/framework/list-sessions';
import { listUsers } from '../fn/framework/list-users';
import { ListUsers$Params } from '../fn/framework/list-users';
import { login } from '../fn/framework/login';
import { Login$Params } from '../fn/framework/login';
import { logout } from '../fn/framework/logout';
import { Logout$Params } from '../fn/framework/logout';
import { manageInvitation } from '../fn/framework/manage-invitation';
import { ManageInvitation$Params } from '../fn/framework/manage-invitation';
import { MfaEnrollment } from '../models/mfa-enrollment';
import { PageOfUserDto } from '../models/page-of-user-dto';
import { passkeyLogin } from '../fn/framework/passkey-login';
import { PasskeyLogin$Params } from '../fn/framework/passkey-login';
import { passkeyLoginOptions } from '../fn/framework/passkey-login-options';
import { PasskeyLoginOptions$Params } from '../fn/framework/passkey-login-options';
import { passkeyMfaOptions } from '../fn/framework/passkey-mfa-options';
import { PasskeyMfaOptions$Params } from '../fn/framework/passkey-mfa-options';
import { PasskeyOptions } from '../models/passkey-options';
import { passkeyRegistrationOptions } from '../fn/framework/passkey-registration-options';
import { PasskeyRegistrationOptions$Params } from '../fn/framework/passkey-registration-options';
import { ProfileResponse } from '../models/profile-response';
import { refresh } from '../fn/framework/refresh';
import { Refresh$Params } from '../fn/framework/refresh';
import { registerAccount } from '../fn/framework/register-account';
import { RegisterAccount$Params } from '../fn/framework/register-account';
import { registerPasskey } from '../fn/framework/register-passkey';
import { RegisterPasskey$Params } from '../fn/framework/register-passkey';
import { RegistrationSettings } from '../models/registration-settings';
import { removePasskey } from '../fn/framework/remove-passkey';
import { RemovePasskey$Params } from '../fn/framework/remove-passkey';
import { replayDelivery } from '../fn/framework/replay-delivery';
import { ReplayDelivery$Params } from '../fn/framework/replay-delivery';
import { resetPassword } from '../fn/framework/reset-password';
import { ResetPassword$Params } from '../fn/framework/reset-password';
import { revokeSession } from '../fn/framework/revoke-session';
import { RevokeSession$Params } from '../fn/framework/revoke-session';
import { rotateRecoveryCodes } from '../fn/framework/rotate-recovery-codes';
import { RotateRecoveryCodes$Params } from '../fn/framework/rotate-recovery-codes';
import { SecuritySettings } from '../models/security-settings';
import { sendEmailMfaCode } from '../fn/framework/send-email-mfa-code';
import { SendEmailMfaCode$Params } from '../fn/framework/send-email-mfa-code';
import { SessionDto } from '../models/session-dto';
import { setCulture } from '../fn/framework/set-culture';
import { SetCulture$Params } from '../fn/framework/set-culture';
import { setMfaPreference } from '../fn/framework/set-mfa-preference';
import { SetMfaPreference$Params } from '../fn/framework/set-mfa-preference';
import { setSecuritySettings } from '../fn/framework/set-security-settings';
import { SetSecuritySettings$Params } from '../fn/framework/set-security-settings';
import { triggerMaintenance } from '../fn/framework/trigger-maintenance';
import { TriggerMaintenance$Params } from '../fn/framework/trigger-maintenance';
import { updateUser } from '../fn/framework/update-user';
import { UpdateUser$Params } from '../fn/framework/update-user';
import { UserDto } from '../models/user-dto';

@Injectable({ providedIn: 'root' })
export class FrameworkService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `getCsrfToken()` */
  static readonly GetCsrfTokenPath = '/api/v1/auth/csrf';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getCsrfToken()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCsrfToken$Response(params?: GetCsrfToken$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = getCsrfToken(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getCsrfToken$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getCsrfToken(params?: GetCsrfToken$Params, context?: HttpContext): Observable<void> {
    const resp = this.getCsrfToken$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getRegistrationSettings()` */
  static readonly GetRegistrationSettingsPath = '/api/v1/auth/registration';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getRegistrationSettings()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRegistrationSettings$Response(params?: GetRegistrationSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistrationSettings>> {
    const obs = getRegistrationSettings(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getRegistrationSettings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getRegistrationSettings(params?: GetRegistrationSettings$Params, context?: HttpContext): Observable<RegistrationSettings> {
    const resp = this.getRegistrationSettings$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<RegistrationSettings>): RegistrationSettings => r.body)
    );
  }

  /** Path part for operation `registerAccount()` */
  static readonly RegisterAccountPath = '/api/v1/auth/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerAccount()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAccount$Response(params: RegisterAccount$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = registerAccount(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerAccount$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerAccount(params: RegisterAccount$Params, context?: HttpContext): Observable<void> {
    const resp = this.registerAccount$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `login()` */
  static readonly LoginPath = '/api/v1/auth/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `login()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login$Response(params: Login$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessResponse>> {
    const obs = login(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `login$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  login(params: Login$Params, context?: HttpContext): Observable<AccessResponse> {
    const resp = this.login$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AccessResponse>): AccessResponse => r.body)
    );
  }

  /** Path part for operation `refresh()` */
  static readonly RefreshPath = '/api/v1/auth/refresh';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `refresh()` instead.
   *
   * This method doesn't expect any request body.
   */
  refresh$Response(params?: Refresh$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessResponse>> {
    const obs = refresh(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `refresh$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  refresh(params?: Refresh$Params, context?: HttpContext): Observable<AccessResponse> {
    const resp = this.refresh$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AccessResponse>): AccessResponse => r.body)
    );
  }

  /** Path part for operation `logout()` */
  static readonly LogoutPath = '/api/v1/auth/logout';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `logout()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout$Response(params?: Logout$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = logout(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `logout$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  logout(params?: Logout$Params, context?: HttpContext): Observable<void> {
    const resp = this.logout$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listSessions()` */
  static readonly ListSessionsPath = '/api/v1/auth/sessions';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listSessions()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSessions$Response(params?: ListSessions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<SessionDto>>> {
    const obs = listSessions(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listSessions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listSessions(params?: ListSessions$Params, context?: HttpContext): Observable<Array<SessionDto>> {
    const resp = this.listSessions$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<SessionDto>>): Array<SessionDto> => r.body)
    );
  }

  /** Path part for operation `revokeSession()` */
  static readonly RevokeSessionPath = '/api/v1/auth/sessions/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `revokeSession()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeSession$Response(params: RevokeSession$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = revokeSession(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `revokeSession$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  revokeSession(params: RevokeSession$Params, context?: HttpContext): Observable<void> {
    const resp = this.revokeSession$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `forgotPassword()` */
  static readonly ForgotPasswordPath = '/api/v1/auth/forgot-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `forgotPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  forgotPassword$Response(params: ForgotPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = forgotPassword(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `forgotPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  forgotPassword(params: ForgotPassword$Params, context?: HttpContext): Observable<void> {
    const resp = this.forgotPassword$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `confirmEmail()` */
  static readonly ConfirmEmailPath = '/api/v1/auth/confirm-email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `confirmEmail()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  confirmEmail$Response(params: ConfirmEmail$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = confirmEmail(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `confirmEmail$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  confirmEmail(params: ConfirmEmail$Params, context?: HttpContext): Observable<void> {
    const resp = this.confirmEmail$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `resetPassword()` */
  static readonly ResetPasswordPath = '/api/v1/auth/reset-password';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `resetPassword()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword$Response(params: ResetPassword$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = resetPassword(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `resetPassword$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  resetPassword(params: ResetPassword$Params, context?: HttpContext): Observable<void> {
    const resp = this.resetPassword$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `setCulture()` */
  static readonly SetCulturePath = '/api/v1/auth/culture';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setCulture()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setCulture$Response(params: SetCulture$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = setCulture(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setCulture$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setCulture(params: SetCulture$Params, context?: HttpContext): Observable<void> {
    const resp = this.setCulture$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `completeMfa()` */
  static readonly CompleteMfaPath = '/api/v1/auth/mfa/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `completeMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  completeMfa$Response(params: CompleteMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessResponse>> {
    const obs = completeMfa(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `completeMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  completeMfa(params: CompleteMfa$Params, context?: HttpContext): Observable<AccessResponse> {
    const resp = this.completeMfa$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AccessResponse>): AccessResponse => r.body)
    );
  }

  /** Path part for operation `sendEmailMfaCode()` */
  static readonly SendEmailMfaCodePath = '/api/v1/auth/mfa/email';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `sendEmailMfaCode()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendEmailMfaCode$Response(params: SendEmailMfaCode$Params, context?: HttpContext): Observable<StrictHttpResponse<EmailMfaChallengeResponse>> {
    const obs = sendEmailMfaCode(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `sendEmailMfaCode$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  sendEmailMfaCode(params: SendEmailMfaCode$Params, context?: HttpContext): Observable<EmailMfaChallengeResponse> {
    const resp = this.sendEmailMfaCode$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<EmailMfaChallengeResponse>): EmailMfaChallengeResponse => r.body)
    );
  }

  /** Path part for operation `getProfile()` */
  static readonly GetProfilePath = '/api/v1/auth/profile';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getProfile()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProfile$Response(params?: GetProfile$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfileResponse>> {
    const obs = getProfile(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getProfile$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getProfile(params?: GetProfile$Params, context?: HttpContext): Observable<ProfileResponse> {
    const resp = this.getProfile$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<ProfileResponse>): ProfileResponse => r.body)
    );
  }

  /** Path part for operation `setMfaPreference()` */
  static readonly SetMfaPreferencePath = '/api/v1/auth/mfa/preference';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setMfaPreference()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setMfaPreference$Response(params: SetMfaPreference$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = setMfaPreference(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setMfaPreference$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setMfaPreference(params: SetMfaPreference$Params, context?: HttpContext): Observable<void> {
    const resp = this.setMfaPreference$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `beginMfaEnrollment()` */
  static readonly BeginMfaEnrollmentPath = '/api/v1/auth/mfa/enroll';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `beginMfaEnrollment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  beginMfaEnrollment$Response(params: BeginMfaEnrollment$Params, context?: HttpContext): Observable<StrictHttpResponse<MfaEnrollment>> {
    const obs = beginMfaEnrollment(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `beginMfaEnrollment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  beginMfaEnrollment(params: BeginMfaEnrollment$Params, context?: HttpContext): Observable<MfaEnrollment> {
    const resp = this.beginMfaEnrollment$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<MfaEnrollment>): MfaEnrollment => r.body)
    );
  }

  /** Path part for operation `confirmMfaEnrollment()` */
  static readonly ConfirmMfaEnrollmentPath = '/api/v1/auth/mfa/confirm';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `confirmMfaEnrollment()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  confirmMfaEnrollment$Response(params: ConfirmMfaEnrollment$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    const obs = confirmMfaEnrollment(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `confirmMfaEnrollment$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  confirmMfaEnrollment(params: ConfirmMfaEnrollment$Params, context?: HttpContext): Observable<Array<string>> {
    const resp = this.confirmMfaEnrollment$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `disableMfa()` */
  static readonly DisableMfaPath = '/api/v1/auth/mfa/disable';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `disableMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  disableMfa$Response(params: DisableMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    const obs = disableMfa(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `disableMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  disableMfa(params: DisableMfa$Params, context?: HttpContext): Observable<Array<string>> {
    const resp = this.disableMfa$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `rotateRecoveryCodes()` */
  static readonly RotateRecoveryCodesPath = '/api/v1/auth/mfa/recovery';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `rotateRecoveryCodes()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rotateRecoveryCodes$Response(params: RotateRecoveryCodes$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<string>>> {
    const obs = rotateRecoveryCodes(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `rotateRecoveryCodes$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  rotateRecoveryCodes(params: RotateRecoveryCodes$Params, context?: HttpContext): Observable<Array<string>> {
    const resp = this.rotateRecoveryCodes$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<string>>): Array<string> => r.body)
    );
  }

  /** Path part for operation `passkeyLoginOptions()` */
  static readonly PasskeyLoginOptionsPath = '/api/v1/auth/passkeys/options';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `passkeyLoginOptions()` instead.
   *
   * This method doesn't expect any request body.
   */
  passkeyLoginOptions$Response(params?: PasskeyLoginOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<PasskeyOptions>> {
    const obs = passkeyLoginOptions(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `passkeyLoginOptions$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  passkeyLoginOptions(params?: PasskeyLoginOptions$Params, context?: HttpContext): Observable<PasskeyOptions> {
    const resp = this.passkeyLoginOptions$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PasskeyOptions>): PasskeyOptions => r.body)
    );
  }

  /** Path part for operation `passkeyLogin()` */
  static readonly PasskeyLoginPath = '/api/v1/auth/passkeys/login';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `passkeyLogin()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  passkeyLogin$Response(params: PasskeyLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessResponse>> {
    const obs = passkeyLogin(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `passkeyLogin$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  passkeyLogin(params: PasskeyLogin$Params, context?: HttpContext): Observable<AccessResponse> {
    const resp = this.passkeyLogin$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AccessResponse>): AccessResponse => r.body)
    );
  }

  /** Path part for operation `passkeyMfaOptions()` */
  static readonly PasskeyMfaOptionsPath = '/api/v1/auth/passkeys/mfa-options';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `passkeyMfaOptions()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  passkeyMfaOptions$Response(params: PasskeyMfaOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<PasskeyOptions>> {
    const obs = passkeyMfaOptions(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `passkeyMfaOptions$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  passkeyMfaOptions(params: PasskeyMfaOptions$Params, context?: HttpContext): Observable<PasskeyOptions> {
    const resp = this.passkeyMfaOptions$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PasskeyOptions>): PasskeyOptions => r.body)
    );
  }

  /** Path part for operation `completePasskeyMfa()` */
  static readonly CompletePasskeyMfaPath = '/api/v1/auth/passkeys/mfa';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `completePasskeyMfa()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  completePasskeyMfa$Response(params: CompletePasskeyMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessResponse>> {
    const obs = completePasskeyMfa(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `completePasskeyMfa$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  completePasskeyMfa(params: CompletePasskeyMfa$Params, context?: HttpContext): Observable<AccessResponse> {
    const resp = this.completePasskeyMfa$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AccessResponse>): AccessResponse => r.body)
    );
  }

  /** Path part for operation `passkeyRegistrationOptions()` */
  static readonly PasskeyRegistrationOptionsPath = '/api/v1/auth/passkeys/register-options';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `passkeyRegistrationOptions()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  passkeyRegistrationOptions$Response(params: PasskeyRegistrationOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<PasskeyOptions>> {
    const obs = passkeyRegistrationOptions(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `passkeyRegistrationOptions$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  passkeyRegistrationOptions(params: PasskeyRegistrationOptions$Params, context?: HttpContext): Observable<PasskeyOptions> {
    const resp = this.passkeyRegistrationOptions$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PasskeyOptions>): PasskeyOptions => r.body)
    );
  }

  /** Path part for operation `registerPasskey()` */
  static readonly RegisterPasskeyPath = '/api/v1/auth/passkeys/register';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `registerPasskey()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerPasskey$Response(params: RegisterPasskey$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = registerPasskey(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `registerPasskey$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  registerPasskey(params: RegisterPasskey$Params, context?: HttpContext): Observable<void> {
    const resp = this.registerPasskey$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `removePasskey()` */
  static readonly RemovePasskeyPath = '/api/v1/auth/passkeys/remove';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `removePasskey()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  removePasskey$Response(params: RemovePasskey$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = removePasskey(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `removePasskey$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  removePasskey(params: RemovePasskey$Params, context?: HttpContext): Observable<void> {
    const resp = this.removePasskey$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getSecuritySettings()` */
  static readonly GetSecuritySettingsPath = '/api/v1/auth/settings/security';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getSecuritySettings()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSecuritySettings$Response(params?: GetSecuritySettings$Params, context?: HttpContext): Observable<StrictHttpResponse<SecuritySettings>> {
    const obs = getSecuritySettings(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getSecuritySettings$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getSecuritySettings(params?: GetSecuritySettings$Params, context?: HttpContext): Observable<SecuritySettings> {
    const resp = this.getSecuritySettings$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SecuritySettings>): SecuritySettings => r.body)
    );
  }

  /** Path part for operation `setSecuritySettings()` */
  static readonly SetSecuritySettingsPath = '/api/v1/auth/settings/security';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `setSecuritySettings()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setSecuritySettings$Response(params: SetSecuritySettings$Params, context?: HttpContext): Observable<StrictHttpResponse<SecuritySettings>> {
    const obs = setSecuritySettings(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `setSecuritySettings$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  setSecuritySettings(params: SetSecuritySettings$Params, context?: HttpContext): Observable<SecuritySettings> {
    const resp = this.setSecuritySettings$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<SecuritySettings>): SecuritySettings => r.body)
    );
  }

  /** Path part for operation `getDeliveryOperations()` */
  static readonly GetDeliveryOperationsPath = '/api/v1/auth/operations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getDeliveryOperations()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDeliveryOperations$Response(params?: GetDeliveryOperations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<DeliverySummary>>> {
    const obs = getDeliveryOperations(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getDeliveryOperations$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getDeliveryOperations(params?: GetDeliveryOperations$Params, context?: HttpContext): Observable<Array<DeliverySummary>> {
    const resp = this.getDeliveryOperations$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<Array<DeliverySummary>>): Array<DeliverySummary> => r.body)
    );
  }

  /** Path part for operation `replayDelivery()` */
  static readonly ReplayDeliveryPath = '/api/v1/auth/operations/replay';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `replayDelivery()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  replayDelivery$Response(params: ReplayDelivery$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = replayDelivery(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `replayDelivery$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  replayDelivery(params: ReplayDelivery$Params, context?: HttpContext): Observable<void> {
    const resp = this.replayDelivery$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `manageInvitation()` */
  static readonly ManageInvitationPath = '/api/v1/auth/invitations';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `manageInvitation()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  manageInvitation$Response(params: ManageInvitation$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = manageInvitation(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `manageInvitation$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  manageInvitation(params: ManageInvitation$Params, context?: HttpContext): Observable<void> {
    const resp = this.manageInvitation$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `listUsers()` */
  static readonly ListUsersPath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listUsers()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUsers$Response(params?: ListUsers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfUserDto>> {
    const obs = listUsers(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listUsers$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listUsers(params?: ListUsers$Params, context?: HttpContext): Observable<PageOfUserDto> {
    const resp = this.listUsers$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageOfUserDto>): PageOfUserDto => r.body)
    );
  }

  /** Path part for operation `createUser()` */
  static readonly CreateUserPath = '/api/v1/users';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser$Response(params: CreateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    const obs = createUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createUser(params: CreateUser$Params, context?: HttpContext): Observable<UserDto> {
    const resp = this.createUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `updateUser()` */
  static readonly UpdateUserPath = '/api/v1/users/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `updateUser()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser$Response(params: UpdateUser$Params, context?: HttpContext): Observable<StrictHttpResponse<UserDto>> {
    const obs = updateUser(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `updateUser$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  updateUser(params: UpdateUser$Params, context?: HttpContext): Observable<UserDto> {
    const resp = this.updateUser$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<UserDto>): UserDto => r.body)
    );
  }

  /** Path part for operation `triggerMaintenance()` */
  static readonly TriggerMaintenancePath = '/api/v1/jobs/maintenance';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `triggerMaintenance()` instead.
   *
   * This method doesn't expect any request body.
   */
  triggerMaintenance$Response(params?: TriggerMaintenance$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = triggerMaintenance(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `triggerMaintenance$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  triggerMaintenance(params?: TriggerMaintenance$Params, context?: HttpContext): Observable<void> {
    const resp = this.triggerMaintenance$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getFeatures()` */
  static readonly GetFeaturesPath = '/api/v1/features';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getFeatures()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeatures$Response(params?: GetFeatures$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = getFeatures(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getFeatures$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getFeatures(params?: GetFeatures$Params, context?: HttpContext): Observable<void> {
    const resp = this.getFeatures$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

  /** Path part for operation `getAdminBootstrapStatus()` */
  static readonly GetAdminBootstrapStatusPath = '/api/v1/bootstrap/status';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getAdminBootstrapStatus()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAdminBootstrapStatus$Response(params?: GetAdminBootstrapStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminBootstrapStatus>> {
    const obs = getAdminBootstrapStatus(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getAdminBootstrapStatus$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getAdminBootstrapStatus(params?: GetAdminBootstrapStatus$Params, context?: HttpContext): Observable<AdminBootstrapStatus> {
    const resp = this.getAdminBootstrapStatus$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<AdminBootstrapStatus>): AdminBootstrapStatus => r.body)
    );
  }

  /** Path part for operation `createBootstrapAdministrator()` */
  static readonly CreateBootstrapAdministratorPath = '/api/v1/bootstrap';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `createBootstrapAdministrator()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBootstrapAdministrator$Response(params: CreateBootstrapAdministrator$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
    const obs = createBootstrapAdministrator(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `createBootstrapAdministrator$Response()` instead.
   *
   * This method sends `application/json` and handles request body of type `application/json`.
   */
  createBootstrapAdministrator(params: CreateBootstrapAdministrator$Params, context?: HttpContext): Observable<void> {
    const resp = this.createBootstrapAdministrator$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<void>): void => r.body)
    );
  }

}
