/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { Observable } from 'rxjs';
import { map } from 'rxjs/operators';

import { BaseService } from '../base-service';
import { ApiConfiguration } from '../api-configuration';
import { StrictHttpResponse } from '../strict-http-response';

import { getPublicContent } from '../fn/public-cms/get-public-content';
import { GetPublicContent$Params } from '../fn/public-cms/get-public-content';
import { listPublicContent } from '../fn/public-cms/list-public-content';
import { ListPublicContent$Params } from '../fn/public-cms/list-public-content';
import { PageOfPublishedContent } from '../models/page-of-published-content';
import { PublishedContent } from '../models/published-content';

@Injectable({ providedIn: 'root' })
export class PublicCmsService extends BaseService {
  constructor(config: ApiConfiguration, http: HttpClient) {
    super(config, http);
  }

  /** Path part for operation `listPublicContent()` */
  static readonly ListPublicContentPath = '/api/public/cms/collections/{key}/items';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `listPublicContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  listPublicContent$Response(params: ListPublicContent$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfPublishedContent>> {
    const obs = listPublicContent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `listPublicContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  listPublicContent(params: ListPublicContent$Params, context?: HttpContext): Observable<PageOfPublishedContent> {
    const resp = this.listPublicContent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PageOfPublishedContent>): PageOfPublishedContent => r.body)
    );
  }

  /** Path part for operation `getPublicContent()` */
  static readonly GetPublicContentPath = '/api/public/cms/collections/{key}/items/{id}';

  /**
   * This method provides access to the full `HttpResponse`, allowing access to response headers.
   * To access only the response body, use `getPublicContent()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublicContent$Response(params: GetPublicContent$Params, context?: HttpContext): Observable<StrictHttpResponse<PublishedContent>> {
    const obs = getPublicContent(this.http, this.rootUrl, params, context);
    return obs;
  }

  /**
   * This method provides access only to the response body.
   * To access the full response (for headers, for example), `getPublicContent$Response()` instead.
   *
   * This method doesn't expect any request body.
   */
  getPublicContent(params: GetPublicContent$Params, context?: HttpContext): Observable<PublishedContent> {
    const resp = this.getPublicContent$Response(params, context);
    return resp.pipe(
      map((r: StrictHttpResponse<PublishedContent>): PublishedContent => r.body)
    );
  }

}
