// <auto-generated />
namespace TemplateV4.Application.Modules;

public static class ModuleIds
{
    public const string AuditHistory = "audit-history";
    public const string AuditRecording = "audit-recording";
    public const string Billing = "billing";
    public const string Delivery = "delivery";
    public const string Identity = "identity";
    public const string Maintenance = "maintenance";
    public const string MyFiles = "my-files";
    public const string Operations = "operations";
    public const string Organizations = "organizations";
    public const string Support = "support";
}

public static class CapabilityIds
{
    public const string AuditHistory = "audit-history";
    public const string AuditRecording = "audit-recording";
    public const string Billing = "billing";
    public const string Delivery = "delivery";
    public const string Identity = "identity";
    public const string Maintenance = "maintenance";
    public const string MyFiles = "my-files";
    public const string Operations = "operations";
    public const string OrganizationFiles = "organization-files";
    public const string Organizations = "organizations";
    public const string Support = "support";
}
