// <auto-generated />
namespace TemplateV4.Application.Modules;

public static class ModuleIds
{
    public const string AuditHistory = "audit-history";
    public const string AuditRecording = "audit-recording";
    public const string Billing = "billing";
    public const string Cms = "cms";
    public const string Contact = "contact";
    public const string Crm = "crm";
    public const string Delivery = "delivery";
    public const string Identity = "identity";
    public const string Invoicing = "invoicing";
    public const string Maintenance = "maintenance";
    public const string MyFiles = "my-files";
    public const string Operations = "operations";
    public const string Organisations = "organisations";
    public const string Support = "support";
}

public static class CapabilityIds
{
    public const string AuditHistory = "audit-history";
    public const string AuditRecording = "audit-recording";
    public const string Billing = "billing";
    public const string Cms = "cms";
    public const string Contact = "contact";
    public const string Crm = "crm";
    public const string CrmFiles = "crm-files";
    public const string Delivery = "delivery";
    public const string Identity = "identity";
    public const string Invoicing = "invoicing";
    public const string InvoicingFiles = "invoicing-files";
    public const string Maintenance = "maintenance";
    public const string MyFiles = "my-files";
    public const string Operations = "operations";
    public const string OrganisationFiles = "organisation-files";
    public const string Organisations = "organisations";
    public const string Support = "support";
}
