/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonElement } from '../models/json-element';
export interface PasskeyOptions {
  challengeId: string;
  options: JsonElement;
}
