/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PasskeySummary } from '../models/passkey-summary';
export interface ProfileResponse {
  culture: string;
  displayName: string;
  email: string;
  id: string;
  mfaEnabled: boolean;
  mfaRequired: boolean;
  passkeys: Array<PasskeySummary>;
  recoveryCodes: number;
  roles: Array<string>;
}
