/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityProof } from '../models/security-proof';
export interface RemovePasskeyRequest {
  id: string;
  proof: SecurityProof;
}
