/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SecuritySettings {
  bootstrapCompletedAt?: (string | null);
  id?: number;
  mfaPolicy?: string;
  version?: string;
}
