/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionDto {
  createdAt: string;
  current: boolean;
  device: string;
  expiresAt: string;
  id: string;
}
