/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserDto {
  culture: string;
  disabled: boolean;
  displayName: string;
  email: string;
  id: string;
  roles: Array<string>;
  status?: string;
  version: string;
}
