<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <Content Include="EmailTemplates/*.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <EmbeddedResource Include="Persistence/Migrations/quartz-3.20.1.sql" />

    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../TemplateV4.Application/TemplateV4.Application.csproj" />

    <PackageReference Include="MailKit" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" PrivateAssets="all" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
  </ItemGroup>
</Project>
