<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <PackageId>templatev4.Framework.Core</PackageId>
    <Version>0.1.0</Version>
    <Description>Provider-independent CQRS, results, authorization, messaging and storage extension contracts.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>
  <ItemGroup><None Include="README.md" Pack="true" PackagePath="/" /></ItemGroup>
</Project>
