<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><IsPackable>true</IsPackable><Version>0.2.0</Version></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../TemplateV4.ModuleContracts/TemplateV4.ModuleContracts.csproj" />
    <Compile Remove="**/*Permissions.cs" />
  </ItemGroup>
</Project>
