FROM mcr.microsoft.com/dotnet/sdk:10.0.401 AS build
ARG PROJECT=TemplateV4.ApiService
WORKDIR /source
COPY . .
RUN dotnet restore src/${PROJECT}/${PROJECT}.csproj --locked-mode
RUN dotnet publish src/${PROJECT}/${PROJECT}.csproj -c Release --no-restore -o /app /p:UseAppHost=false
RUN cp /app/${PROJECT}.dll /app/entry.dll && cp /app/${PROJECT}.deps.json /app/entry.deps.json && cp /app/${PROJECT}.runtimeconfig.json /app/entry.runtimeconfig.json
RUN mkdir /keys
FROM mcr.microsoft.com/dotnet/aspnet:10.0.12-noble-chiseled-extra
ARG PROJECT=TemplateV4.ApiService
WORKDIR /app
COPY --from=build /app .
COPY --from=build --chown=1654:1654 /keys /keys
ENV ASPNETCORE_HTTP_PORTS=8080
USER $APP_UID
EXPOSE 8080
ENTRYPOINT ["dotnet", "entry.dll"]
