/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PermissionItem } from '../models/permission-item';
import { RoleItem } from '../models/role-item';
export interface AccessCatalog {
  permissions: Array<PermissionItem>;
  roles: Array<RoleItem>;
}
