/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ActionItemDto {
  assignee: string;
  assigneeId: (string | null);
  canComplete: boolean;
  completedAt: (string | null);
  createdAt: string;
  description: string;
  id: string;
  link: string;
  queueId: (string | null);
  source: string;
  state: string;
  title: string;
}
