/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ApiKeyItem } from '../models/api-key-item';
export interface ApiKeyPage {
  items: Array<ApiKeyItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
