/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ArticleContent {
  author: string;
  excerpt: string;
  markdown: string;
  slug: string;
  title: string;
}
