/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AuditItem {
  action: string;
  actorId: (string | null);
  actorName: (string | null);
  at: string;
  id: number;
  subjectId: (string | null);
  subjectName: (string | null);
}
