/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditChange } from '../models/audit-change';
import { AuditItem } from '../models/audit-item';
import { AuditRelatedEntity } from '../models/audit-related-entity';
export interface AuditDetail {
  actorType: (string | null);
  changes: Array<AuditChange>;
  entry: AuditItem;
  failureCode: (string | null);
  metadata: {
[key: string]: string;
};
  outcome: (string | null);
  reason: (string | null);
  relatedEntities: Array<AuditRelatedEntity>;
  schemaVersion: (number | null);
  source: (string | null);
  subjectType: (string | null);
  traceParent: (string | null);
}
