/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BackgroundJobRun {
  attempts: number;
  availableAt: string;
  completedAt: (string | null);
  culture: string;
  errorCode: (string | null);
  id: string;
  state: string;
}
