/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BackgroundJobSummary } from '../models/background-job-summary';
export interface BackgroundJobPage {
  items: Array<BackgroundJobSummary>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
