/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BackgroundJobRun } from '../models/background-job-run';
import { BackgroundJobSummary } from '../models/background-job-summary';
export interface BackgroundJobDetail {
  hasPayload: boolean;
  history: Array<BackgroundJobRun>;
  job: BackgroundJobSummary;
  retentionDays: number;
}
