/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BillingPlan {
  currency: string;
  id: string;
  monthlyMinor: number;
  name: string;
  pricing: string;
  storageBytes: number;
  yearlyMinor: number;
}
