/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BillingPlan } from '../models/billing-plan';
import { BillingSettings } from '../models/billing-settings';
export interface BillingSummary {
  canCancel: boolean;
  canCheckout: boolean;
  canManage: boolean;
  customerId: string;
  entitlementState: string;
  interval: (string | null);
  paidUntil: (string | null);
  planId: string;
  plans: Array<BillingPlan>;
  provider: (string | null);
  seats: number;
  settings: BillingSettings;
  state: string;
  storageBytes: number;
  trialUntil: (string | null);
}
