/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BillingSettings {
  defaultProvider: string;
  graceDays: number;
  ownership: string;
  payFastEnabled: boolean;
  stripeEnabled: boolean;
  trialDays: number;
  version: string;
}
