/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlogSummary } from '../models/blog-summary';
export interface BlogArticle {
  article: BlogSummary;
  html: string;
}
