/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BusinessDetails {
  address: string;
  adminUrl: string;
  description: string;
  email: string;
  logoUrl: string;
  name: string;
  phone: string;
  primaryColor: string;
  publicUrl: string;
  seoDescription: string;
  seoTitle: string;
}
