/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SecurityProof } from '../models/security-proof';
export interface ChangeEmailRequest {
  email: string;
  proof: SecurityProof;
}
