/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CheckoutResponse {
  fields: ({
[key: string]: string;
} | null);
  id: string;
  reference?: (string | null);
  url: string;
}
