/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CmsArticleSummary {
  id: string;
  pendingChanges: boolean;
  published: boolean;
  title: string;
  updatedAt: string;
}
