/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LandingSection } from '../models/landing-section';
export interface CmsSections {
  draft: Array<LandingSection>;
  published: Array<LandingSection>;
  version: string;
}
