/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PricedLine } from '../models/priced-line';
export interface CommercialTotals {
  lines: Array<PricedLine>;
  net: number;
  tax: number;
  total: number;
}
