/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialDocument } from '../models/commercial-document';
import { FinancialEntry } from '../models/financial-entry';
export interface CommercialDetail {
  document: CommercialDocument;
  entries: Array<FinancialEntry>;
  related: Array<CommercialDocument>;
}
