/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialTotals } from '../models/commercial-totals';
import { CrmRecordInput } from '../models/crm-record-input';
import { IssuerSettings } from '../models/issuer-settings';
export interface CommercialSnapshot {
  customer: CrmRecordInput;
  issuer: IssuerSettings;
  organisationLogoId?: (string | null);
  organisationName?: (string | null);
  reference: (string | null);
  totals: CommercialTotals;
}
