/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ChargeCategory } from '../models/charge-category';
import { TaxTreatment } from '../models/tax-treatment';
export interface CommercialLine {
  category: ChargeCategory;
  description: string;
  quantity: number;
  taxRate: number;
  taxTreatment: TaxTreatment;
  unitPrice: number;
}
