/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommercialPlanPrice {
  currency: string;
  effectiveFrom: string;
  id: string;
  monthlyMinor: number;
  yearlyMinor: number;
}
