/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommercialCheckoutRequest {
  interval: string;
  planId: string;
  provider: string;
  requestId: string;
  seats: number;
}
