/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialPlanPrice } from '../models/commercial-plan-price';
export interface CommercialPlan {
  id: string;
  name: string;
  price: CommercialPlanPrice;
  pricing: string;
  storageBytes: number;
}
