/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialBillingSettings } from '../models/commercial-billing-settings';
import { CommercialEntitlement } from '../models/commercial-entitlement';
import { CommercialInvoice } from '../models/commercial-invoice';
import { CommercialPaymentReceipt } from '../models/commercial-payment-receipt';
import { CommercialPlan } from '../models/commercial-plan';
import { CommercialUsage } from '../models/commercial-usage';
import { PaymentMethodStatus } from '../models/payment-method-status';
export interface CommercialBillingSummary {
  canCancel: boolean;
  canCheckout: boolean;
  canManage: boolean;
  customerId: string;
  entitlements: Array<CommercialEntitlement>;
  interval: (string | null);
  invoices: Array<CommercialInvoice>;
  paidUntil: (string | null);
  paymentMethods: PaymentMethodStatus;
  planId: string;
  plans: Array<CommercialPlan>;
  provider: (string | null);
  receipts: Array<CommercialPaymentReceipt>;
  seats: number;
  settings: CommercialBillingSettings;
  state: string;
  trialUntil: (string | null);
  usage: Array<CommercialUsage>;
}
