/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommercialInvoice {
  currency: string;
  id: string;
  issuedAt: string;
  number: string;
  paidAt: (string | null);
  periodEnd: (string | null);
  periodStart: (string | null);
  state: string;
  totalMinor: number;
}
