/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ManualPaymentMethod } from '../models/manual-payment-method';
export interface CommercialAction {
  amount: number;
  date: string;
  idempotencyKey: string;
  method: ManualPaymentMethod;
  reason: string;
  reference: (string | null);
  version: string;
}
