/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentAccessOption } from '../models/content-access-option';
export interface ContentAccessOptions {
  roles: Array<ContentAccessOption>;
  users: Array<ContentAccessOption>;
}
