/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContentItemSummary {
  id: string;
  published: boolean;
  state: string;
  title: string;
  updatedAt: string;
}
