/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentDecision } from '../models/content-decision';
export interface ContentItem {
  actions: Array<string>;
  collection: string;
  decisions: Array<ContentDecision>;
  id: string;
  pendingChanges: boolean;
  published: boolean;
  publishedAt: (string | null);
  revisionId: string;
  state: string;
  title: string;
  updatedAt: string;

  /**
   * Values keyed by the collection's stable field keys. Values follow its versioned field schema.
   */
  values: {
[key: string]: any;
};
  version: string;
}
