/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentField } from '../models/content-field';
import { ContentGrant } from '../models/content-grant';
import { ContentWorkflow } from '../models/content-workflow';
export interface ContentCollection {
  actions: Array<string>;
  fields: Array<ContentField>;
  grants: Array<ContentGrant>;
  key: string;
  label: string;
  publicRead: boolean;
  version: string;
  workflow: ContentWorkflow;
}
