/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContactEnquiry {
  createdAt: string;
  email: string;
  id: string;
  message: string;
  name: string;
  read: boolean;
}
