/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ContentWorkflow {
  approvals?: number;
  autoPublish?: boolean;
  required?: boolean;
  roles?: (Array<string> | null);
  users?: (Array<string> | null);
}
