/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateTicket {
  categoryId: (string | null);
  description: string;
  draft?: boolean;
  subject: string;
}
