/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateApiKey {
  collections?: (Array<string> | null);
  expiresInDays: (number | null);
  name: string;
  scopes: Array<string>;
}
