/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateActionItem {
  assigneeId?: (string | null);
  description: string;
  link: string;
  queueId?: (string | null);
  title: string;
}
