/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmField } from '../models/crm-field';
import { CrmOption } from '../models/crm-option';
import { CrmPipeline } from '../models/crm-pipeline';
export interface CrmConfiguration {
  contactFields: Array<CrmField>;
  lifecycleStatuses: Array<CrmOption>;
  pipelines: Array<CrmPipeline>;
  tags: Array<CrmOption>;
  version: string;
}
