/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmFieldValue } from '../models/crm-field-value';
import { CrmRecordKind } from '../models/crm-record-kind';
import { CrmRelationship } from '../models/crm-relationship';
import { DealOutcome } from '../models/deal-outcome';
export interface CrmRecordInput {
  address: (string | null);
  companies: Array<CrmRelationship>;
  contactId: (string | null);
  customFields: Array<CrmFieldValue>;
  customerId: (string | null);
  email: (string | null);
  expectedCloseDate: (string | null);
  kind: CrmRecordKind;
  lifecycleStatusId: (string | null);
  name: string;
  outcome: DealOutcome;
  ownerId: (string | null);
  phone: (string | null);
  pipelineId: (string | null);
  stageId: (string | null);
  tags: Array<string>;
  value: (number | null);
  vatNumber?: (string | null);
}
