/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmOption } from '../models/crm-option';
export interface CrmField {
  id: string;
  label: string;
  options: Array<CrmOption>;
  retired?: boolean;
}
