/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmNote } from '../models/crm-note';
import { CrmRecord } from '../models/crm-record';
export interface CrmDetail {
  notes: Array<CrmNote>;
  record: CrmRecord;
}
