/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmStage } from '../models/crm-stage';
export interface CrmPipeline {
  id: string;
  label: string;
  retired?: boolean;
  stages: Array<CrmStage>;
}
