/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmRecordInput } from '../models/crm-record-input';
export interface CrmRecord {
  archived: boolean;
  createdAt: string;
  data: CrmRecordInput;
  id: string;
  organisationId: string;
  updatedAt: string;
  version: string;
}
