/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerInfo {
  id: string;
  kind: string;
  members: number;
  name: string;
  role: string;
  version: string;
}
