/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerInfo {
  canManage: boolean;
  contactEmail: (string | null);
  country: (string | null);
  id: string;
  logoUrl: (string | null);
  name: string;
  primaryContactNumber: (string | null);
  timeZone: string;
  timeZones: Array<string>;
  users: number;
  version: string;
  websiteUrl: (string | null);
}
