/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CustomerInvitation {
  customerId: string;
  customerName: string;
  expiresAt: string;
  id: string;
  role: string;
}
