/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomerInfo } from '../models/customer-info';
import { CustomerInvitation } from '../models/customer-invitation';
export interface CustomerHome {
  accounts: Array<CustomerInfo>;
  invitations: Array<CustomerInvitation>;
  mode: string;
}
