/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardLayout } from '../models/dashboard-layout';
export interface DashboardDto {
  id: string;
  layout: DashboardLayout;
  personalized: boolean;
  shared: boolean;
  version: string;
}
