/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardCard {
  definitionId: string;
  filter: string;
  format: string;
  id: string;
  metric: string;
  period: string;
  size: string;
}
