/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardItem } from '../models/dashboard-item';
import { DashboardPoint } from '../models/dashboard-point';
export interface DashboardCardData {
  items: Array<DashboardItem>;
  points: Array<DashboardPoint>;
  unit: string;
  value: number;
}
