/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardCard } from '../models/dashboard-card';
export interface DashboardLayout {
  cards: Array<DashboardCard>;
  name: string;
  period: string;
}
