/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardCardDefinition } from '../models/dashboard-card-definition';
import { DashboardDto } from '../models/dashboard-dto';
export interface DashboardState {
  canManage: boolean;
  catalog: Array<DashboardCardDefinition>;
  dashboards: Array<DashboardDto>;
  defaults: Array<DashboardDto>;
  startingDashboardId: (string | null);
}
