/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DashboardCardDefinition {
  dateFilter: boolean;
  filters: Array<string>;
  formats: Array<string>;
  id: string;
  metrics: Array<string>;
  module: string;
  sizes: Array<string>;
  title: string;
}
