/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeletionItem {
  displayName: (string | null);
  id: string;
  requestedAt: string;
  reviewedAt: (string | null);
  state: string;
  userId: string;
}
