/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface DeliverySummary {
  attempts: number;
  availableAt: string;
  errorCode: (string | null);
  id: string;
  state: string;
  type: string;
}
