/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileItem } from '../models/file-item';
import { PageOfFileItem } from '../models/page-of-file-item';
export interface FilePage {
  folder: (null | FileItem);
  maxUploadBytes: number;
  ownerName: string;
  page: PageOfFileItem;
  quotaBytes: number;
  quotaOverrideBytes: (number | null);
  usedBytes: number;
}
