/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileItem {
  category?: string;
  contentType: string;
  createdAt: string;
  demoExpiryMinutes?: number;
  demoMode?: boolean;
  fileCount?: number;
  id: string;
  important?: boolean;
  isFolder: boolean;
  itemCount?: number;
  name: string;
  parentId: (string | null);
  permission?: string;
  sharedWithSomeone?: boolean;
  size: number;
  starred?: boolean;
  updatedAt?: (string | null);
}
