/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileStorageSettings {
  defaultQuotaBytes?: number;
  demoExpiryMinutes?: number;
  demoMode?: boolean;
  demoStartedAt?: (string | null);
  id?: number;
  maxUploadBytes?: number;
  slowUploadMode?: boolean;
  version?: string;
}
