/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageOfFileItem } from '../models/page-of-file-item';
export interface FilePage {
  allowedExtensions: Array<string>;
  maxUploadBytes: number;
  page: PageOfFileItem;
  quotaBytes: number;
  usedBytes: number;
}
