/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileShareItem {
  expiresAt: (string | null);
  id: string;
  permission: string;
  recipient: (string | null);
  token?: (string | null);
}
