/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FileItem {
  contentType: string;
  createdAt: string;
  id: string;
  isFolder: boolean;
  name: string;
  parentId: (string | null);
  size: number;
}
