/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InvitationItem {
  acceptedAt: (string | null);
  displayName: string;
  email: string;
  emailConfirmed: boolean;
  expiresAt: (string | null);
  id: string;
  resendAt: (string | null);
  sentAt: (string | null);
  state: string;
}
