/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InvitationItem } from '../models/invitation-item';
export interface InvitationPage {
  accepted: number;
  expired: number;
  items: Array<InvitationItem>;
  pageNumber: number;
  pageSize: number;
  pending: number;
  revoked: number;
  total: number;
}
