/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialDocumentKind } from '../models/commercial-document-kind';
import { CommercialLine } from '../models/commercial-line';
import { CommercialOrigin } from '../models/commercial-origin';
export interface IssueCommercialDocument {
  acceptedQuotationId: (string | null);
  customerId: string;
  idempotencyKey: string;
  kind: CommercialDocumentKind;
  lines: Array<CommercialLine>;
  origin: (null | CommercialOrigin);
  previousRevisionId: (string | null);
  reference: (string | null);
}
