/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface IssuerSettings {
  address: string;
  contact: string;
  name: string;
  numberPrefix: string;
  paymentInstructions: string;
  vatNumber: (string | null);
  vatRegistered: boolean;
  version: string;
}
