/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LandingSection {
  heading: string;
  imageAlt: string;
  imageUrl: string;
  key: string;
  text: string;
}
