/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ModuleActivation {
  available: boolean;
  disableBlockers: Array<string>;
  enableBlockers: Array<string>;
  enabled: boolean;
  id: string;
  version: string;
}
