/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MyFilesModuleSettings {
  demoExpiryMinutes?: number;
  demoMode: boolean;
  slowUploadMode: boolean;
  version: string;
}
