/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageOfNotificationItem } from '../models/page-of-notification-item';
export interface NotificationPage {
  optionalEmailEnabled: boolean;
  page: PageOfNotificationItem;
  unread: number;
}
