/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationItem {
  createdAt: string;
  id: string;
  kind: string;
  link: string;
  readAt: (string | null);
}
