/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { InstalledModule } from '../models/installed-module';
export interface OperationsOverview {
  activeJobs: number;
  backlogWarningSeconds: number;
  checkedAt: string;
  failedJobs: number;
  failedMessages: number;
  lastMaintenanceAt: (string | null);
  modules: Array<InstalledModule>;
  oldestMessageSeconds: number;
  pendingMessages: number;
  version: string;
}
