/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageOfOrganisationFileItem } from '../models/page-of-organisation-file-item';
export interface OrganisationFilePage {
  page: PageOfOrganisationFileItem;
  quotaBytes: number;
  usedBytes: number;
}
