/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CmsArticleSummary } from '../models/cms-article-summary';
export interface PageOfCmsArticleSummary {
  items: Array<CmsArticleSummary>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
