/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CrmRecord } from '../models/crm-record';
export interface PageOfCrmRecord {
  items: Array<CrmRecord>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
