/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganisationAttachment } from '../models/organisation-attachment';
export interface PageOfOrganisationAttachment {
  items: Array<OrganisationAttachment>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
