/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PublishedContent } from '../models/published-content';
export interface PageOfPublishedContent {
  items: Array<PublishedContent>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
