/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ActionItemDto } from '../models/action-item-dto';
export interface PageOfActionItemDto {
  items: Array<ActionItemDto>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
