/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { FileItem } from '../models/file-item';
export interface PageOfFileItem {
  items: Array<FileItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
