/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContactEnquiry } from '../models/contact-enquiry';
export interface PageOfContactEnquiry {
  items: Array<ContactEnquiry>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
