/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RegistrationReviewItem } from '../models/registration-review-item';
export interface PageOfRegistrationReviewItem {
  items: Array<RegistrationReviewItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
