/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeletionItem } from '../models/deletion-item';
export interface PageOfDeletionItem {
  items: Array<DeletionItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
