/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganisationFileItem } from '../models/organisation-file-item';
export interface PageOfOrganisationFileItem {
  items: Array<OrganisationFileItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
