/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AuditItem } from '../models/audit-item';
export interface PageOfAuditItem {
  items: Array<AuditItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
