/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentItemSummary } from '../models/content-item-summary';
export interface PageOfContentItemSummary {
  items: Array<ContentItemSummary>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
