/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { NotificationItem } from '../models/notification-item';
export interface PageOfNotificationItem {
  items: Array<NotificationItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
