/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleItem } from '../models/role-item';
export interface PageOfRoleItem {
  items: Array<RoleItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
