/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketItem } from '../models/ticket-item';
export interface PageOfTicketItem {
  items: Array<TicketItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
