/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganisationUser } from '../models/organisation-user';
export interface PageOfOrganisationUser {
  items: Array<OrganisationUser>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
