/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BlogSummary } from '../models/blog-summary';
export interface PageOfBlogSummary {
  items: Array<BlogSummary>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
