/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TicketMessage } from '../models/ticket-message';
export interface PageOfTicketMessage {
  items: Array<TicketMessage>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
