/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialDocument } from '../models/commercial-document';
export interface PageOfCommercialDocument {
  items: Array<CommercialDocument>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
