/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { OrganizationFileItem } from '../models/organization-file-item';
export interface PageOfOrganizationFileItem {
  items: Array<OrganizationFileItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
