/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { JsonElement } from '../models/json-element';
export interface PasskeyRegistrationCredential {
  challengeId: string;
  credential: JsonElement;
  deviceId: string;
  name: string;
}
