/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentMethodSettings {
  defaultProvider: string;
  payFastEnabled: boolean;
  stripeEnabled: boolean;
  version: string;
}
