/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PaymentMethodStatus {
  defaultProvider: string;
  payFastEnabled: boolean;
  payFastReady: boolean;
  stripeEnabled: boolean;
  stripeReady: boolean;
  version: string;
}
