/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CustomBrandColor } from '../models/custom-brand-color';
export interface PlatformAppearance {
  customColors: Array<CustomBrandColor>;
  primaryColor: string;
  selectedCustomColorId: (string | null);
  version: string;
}
