/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialLine } from '../models/commercial-line';
export interface PreviewCommercialDocument {
  lines: Array<CommercialLine>;
}
