/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommercialLine } from '../models/commercial-line';
export interface PricedLine {
  net: number;
  source: CommercialLine;
  tax: number;
  total: number;
}
