/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DeletionItem } from '../models/deletion-item';
export interface PrivacyStatus {
  deletedFileRetentionDays: number;
  notificationRetentionDays: number;
  request: (null | DeletionItem);
  reviewPolicy?: string;
}
