/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PrivateModuleRegistration {
  appId: string;
  buildToken: string;
  environment: string;
  environmentId: string;
  environmentVariables: Array<string>;
  serviceUrl: string;
}
