/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublishedContent {
  collection: string;
  id: string;
  publishedAt: string;
  updatedAt: string;

  /**
   * Values keyed by the collection's stable field keys. Values follow its versioned field schema.
   */
  values: {
[key: string]: any;
};
}
