/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PublicAppearance {
  loginBackground?: string;
  organisationLogoUrl: (string | null);
  organisationName: string;
  primaryColor: string;
}
