/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RecordAttachment {
  available: boolean;
  fileId: string;
  name: (string | null);
  size: (number | null);
}
