/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RoleItem {
  builtIn: boolean;
  description: string;
  id: string;
  members: number;
  name: string;
  permissions: Array<string>;
  version: string;
}
