/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface RuntimeModule {
  available: boolean;
  demoMode?: boolean;
  enabled: boolean;
  id: string;
  slowUploadMode?: boolean;
  version: string;
}
