/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveContentItem {
  id: (string | null);

  /**
   * Values keyed by the collection's stable field keys. Values follow its versioned field schema.
   */
  values: {
[key: string]: any;
};
  version: (string | null);
}
