/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentGrant } from '../models/content-grant';
export interface SaveContentGrants {
  grants: Array<ContentGrant>;
  version: string;
}
