/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { BusinessDetails } from '../models/business-details';
export interface SaveWebsite {
  details: BusinessDetails;
  version: string;
}
