/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveRuntimeModule {
  demoMode?: (boolean | null);
  enabled: boolean;
  id: string;
  permission?: (string | null);
  slowUploadMode?: (boolean | null);
  version: string;
}
