/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveSupportModuleSettings {
  enquiriesEnabled: boolean;
  notificationEmail: string;
  permission?: (string | null);
  ticketsEnabled: boolean;
  version: string;
}
