/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveFileStorageModuleSettings {
  demoMode: boolean;
  password?: (string | null);
  permission?: (string | null);
  slowUploadMode: boolean;
  version: string;
}
