/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ContentField } from '../models/content-field';
import { ContentWorkflow } from '../models/content-workflow';
export interface SaveCollection {
  fields: Array<ContentField>;
  key: string;
  label: string;
  publicRead?: boolean;
  version: (string | null);
  workflow: ContentWorkflow;
}
