/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { DashboardLayout } from '../models/dashboard-layout';
export interface SaveDashboard {
  id: (string | null);
  layout: DashboardLayout;
  shared: boolean;
  version: (string | null);
}
