/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SaveRoleRequest {
  description: string;
  name: string;
  permissions: Array<string>;
  version?: (string | null);
}
