/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LandingSection } from '../models/landing-section';
export interface SaveCmsSections {
  sections: Array<LandingSection>;
  version: string;
}
