/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionAuditItem } from '../models/session-audit-item';
export interface SessionAuditPage {
  items: Array<SessionAuditItem>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
