/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SessionDto } from '../models/session-dto';
export interface SessionPage {
  items: Array<SessionDto>;
  pageNumber: number;
  pageSize: number;
  total: number;
}
