/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SessionAuditItem {
  action: string;
  at: string;
  id: number;
  outcome: string;
  subjectName: (string | null);
}
