/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface StorageSettingsRequest {
  defaultQuotaBytes: number;
  demoExpiryMinutes?: number;
  maxUploadBytes: number;
  version: string;
}
