/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SupportModuleSettings {
  enquiriesEnabled: boolean;
  notificationEmail: string;
  ticketsEnabled: boolean;
  version: string;
}
