/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { SupportAgent } from '../models/support-agent';
import { SupportCategory } from '../models/support-category';
export interface SupportOptions {
  administrator: boolean;
  agent: boolean;
  agents: Array<SupportAgent>;
  categories: Array<SupportCategory>;
}
