/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TicketItem {
  assignee: (string | null);
  assigneeId: (string | null);
  category: (string | null);
  categoryId: (string | null);
  createdAt: string;
  description: string;
  id: string;
  priority: string;
  referenceNumber: number;
  requester: string;
  requesterId: string;
  status: string;
  subject: string;
  updatedAt: string;
  version: string;
}
