/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageOfTicketMessage } from '../models/page-of-ticket-message';
import { TicketAttachment } from '../models/ticket-attachment';
import { TicketItem } from '../models/ticket-item';
export interface TicketDetail {
  agent: boolean;
  attachments: Array<TicketAttachment>;
  description: string;
  messages: PageOfTicketMessage;
  ticket: TicketItem;
}
