/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateOrganisation {
  contactEmail: (string | null);
  country: (string | null);
  name: string;
  primaryContactNumber: (string | null);
  timeZone: string;
  version: string;
  websiteUrl: (string | null);
}
