/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateProfileRequest {
  avatarBase64?: (string | null);
  culture: string;
  displayName: string;
  firstName: (string | null);
  lastName: (string | null);
  phoneNumber: (string | null);
  removeAvatar?: boolean;
  timeZone: string;
  version: string;
}
