/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateUser {
  disabled: boolean;
  id: string;
  permission?: (string | null);
  roles: Array<string>;
  version: string;
}
