/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateTicket {
  assigneeId: (string | null);
  categoryId: (string | null);
  description?: (string | null);
  id: string;
  priority: string;
  status: string;
  subject?: (string | null);
  version: string;
}
