/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { RoleItem } from '../models/role-item';
import { UserDto } from '../models/user-dto';
export interface UserAccessDetail {
  effectivePermissions: Array<string>;
  roles: Array<RoleItem>;
  user: UserDto;
}
