import { customerTranslations } from './features/organisations/customer-resolver';
import { businessTranslations } from './core/business-translations';
import { administrationLandingGuard, peopleLandingGuard } from './core/administration';
import { capabilityGuard } from './core/features';
import { destinationGuard, workspaceDestinations, administrationDestinations, } from './core/destinations';
import { supportTranslations } from './features/support/support-resolver';
import { inject } from '@angular/core';
import { Router } from '@angular/router';
import { authGuard, permissionGuard } from './core/auth';
import { unsavedGuard } from './shared/confirmation';
import { bootstrapLandingGuard, bootstrapLoginGuard } from './core/bootstrap';
export const routes = [
    {
        path: 'organizations/:id/invoicing',
        resolve: { businessTranslations },
        data: { breadcrumb: 'invoicing' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/invoicing/documents/invoicing').then((m) => m.InvoicingPage),
    },
    {
        path: 'organizations/:id/invoicing/new',
        canDeactivate: [unsavedGuard],
        resolve: { businessTranslations },
        data: { breadcrumb: 'issueDocument' },
        canActivate: [authGuard, capabilityGuard('invoicing')],
        loadComponent: () => import('./features/invoicing/documents/commercial-editor').then((m) => m.CommercialEditorPage),
    },
    {
        path: 'organizations/:id/invoicing/settings',
        canDeactivate: [unsavedGuard],
        resolve: { businessTranslations },
        data: { breadcrumb: 'issuerSettings' },
        canActivate: [authGuard, capabilityGuard('invoicing')],
        loadComponent: () => import('./features/invoicing/configuration/issuer-settings').then((m) => m.IssuerSettingsPage),
    },
    {
        path: 'organizations/:id/invoicing/:documentId',
        resolve: { businessTranslations },
        data: { breadcrumb: 'invoicing' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/invoicing/documents/commercial-detail').then((m) => m.CommercialDetailPage),
    },
    {
        path: 'organizations/:id/crm',
        resolve: { businessTranslations },
        data: { breadcrumb: 'crm' },
        canActivate: [authGuard, capabilityGuard('crm')],
        loadComponent: () => import('./features/crm/records/crm').then((m) => m.CrmPage),
    },
    {
        path: 'organizations/:id/crm/configuration',
        canDeactivate: [unsavedGuard],
        resolve: { businessTranslations },
        data: { breadcrumb: 'crmConfiguration' },
        canActivate: [authGuard, capabilityGuard('crm')],
        loadComponent: () => import('./features/crm/configuration/crm-configuration').then((m) => m.CrmConfigurationPage),
    },
    {
        path: 'organizations/:id/crm/:recordId',
        canDeactivate: [unsavedGuard],
        resolve: { businessTranslations },
        data: { breadcrumb: 'crmEdit' },
        canActivate: [authGuard, capabilityGuard('crm')],
        loadComponent: () => import('./features/crm/records/crm-detail').then((m) => m.CrmDetailPage),
    },
    {
        path: 'files',
        pathMatch: 'full',
        redirectTo: ({ queryParams }) => inject(Router).createUrlTree(['/file-storage'], { queryParams }),
    },
    {
        path: 'shared-files/:id',
        data: { breadcrumb: 'sharedWithMe' },
        loadComponent: () => import('./features/file-storage/sharing/public-file-storage').then((m) => m.PublicFileStoragePage),
    },
    {
        path: 'organizations',
        canDeactivate: [unsavedGuard],
        resolve: { customerTranslations, businessTranslations },
        data: { breadcrumb: 'organizations' },
        canActivate: [authGuard, destinationGuard(workspaceDestinations.organizations)],
        loadComponent: () => import('./features/organisations/organizations').then((m) => m.OrganizationsPage),
    },
    {
        path: 'organizations/:id/billing',
        canDeactivate: [unsavedGuard],
        resolve: { customerTranslations, businessTranslations },
        data: { breadcrumb: 'billing' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/billing/billing').then((m) => m.BillingPage),
    },
    {
        path: 'organizations/:id/files',
        canDeactivate: [unsavedGuard],
        resolve: { customerTranslations, businessTranslations },
        data: { breadcrumb: 'organizationFiles' },
        canActivate: [authGuard, capabilityGuard('organization-files')],
        loadComponent: () => import('./features/organisations/files/organization-files').then((m) => m.OrganizationFilesPage),
    },
    {
        path: 'organizations/:id',
        canDeactivate: [unsavedGuard],
        resolve: { customerTranslations, businessTranslations },
        data: { breadcrumb: 'organizationWorkspace' },
        canActivate: [authGuard, destinationGuard(workspaceDestinations.organizations)],
        loadComponent: () => import('./features/organisations/organization-detail').then((m) => m.OrganizationDetailPage),
    },
    { path: '', pathMatch: 'full', canActivate: [bootstrapLandingGuard], children: [] },
    {
        path: 'dashboard',
        data: { breadcrumb: 'dashboard' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/dashboard/dashboard').then((m) => m.DashboardPage),
    },
    {
        path: 'bootstrap',
        data: { breadcrumb: 'bootstrapTitle' },
        loadComponent: () => import('./features/identity/authentication/bootstrap').then((m) => m.BootstrapPage),
    },
    {
        path: 'login',
        data: { breadcrumb: 'signIn' },
        canActivate: [bootstrapLoginGuard],
        loadComponent: () => import('./features/identity/authentication/login').then((m) => m.LoginPage),
    },
    {
        path: 'signup',
        data: { breadcrumb: 'signupTitle' },
        loadComponent: () => import('./features/identity/authentication/signup').then((m) => m.SignupPage),
    },
    {
        path: 'account',
        data: { breadcrumb: 'account' },
        loadComponent: () => import('./features/identity/account/account').then((m) => m.AccountPage),
    },
    { path: 'profile', redirectTo: 'security', pathMatch: 'full' },
    { path: 'sessions', redirectTo: 'security/sessions', pathMatch: 'full' },
    {
        path: 'me',
        data: { breadcrumb: 'account' },
        canActivate: [authGuard],
        canDeactivate: [unsavedGuard],
        loadComponent: () => import('./features/identity/account/account-home').then((m) => m.AccountHomePage),
    },
    { path: 'users', redirectTo: 'administration/users', pathMatch: 'full' },
    {
        path: 'security/sessions',
        data: { breadcrumb: 'sessions' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/identity/sessions/sessions').then((m) => m.SessionsPage),
    },
    {
        path: 'security',
        data: { breadcrumb: 'security' },
        canDeactivate: [unsavedGuard],
        canActivate: [authGuard],
        loadComponent: () => import('./features/identity/account/profile').then((m) => m.ProfilePage),
    },
    {
        path: 'notifications',
        data: { breadcrumb: 'notificationCentre' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/notifications/notification-centre').then((m) => m.NotificationCentrePage),
        children: [
            {
                path: '',
                pathMatch: 'full',
                data: { breadcrumb: 'inbox' },
                loadComponent: () => import('./features/notifications/inbox').then((m) => m.InboxPage),
            },
            {
                path: 'preferences',
                data: { breadcrumb: 'notificationPreferences' },
                loadComponent: () => import('./features/notifications/notification-preferences').then((m) => m.NotificationPreferencesPage),
            },
        ],
    },
    {
        path: 'support',
        resolve: { supportTranslations },
        runGuardsAndResolvers: 'always',
        data: { breadcrumb: 'support' },
        canActivate: [authGuard, destinationGuard(workspaceDestinations.support)],
        children: [
            {
                path: '',
                canDeactivate: [unsavedGuard],
                loadComponent: () => import('./features/support/tickets/support').then((m) => m.SupportPage),
            },
            {
                path: 'new',
                data: { breadcrumb: 'supportNew' },
                canDeactivate: [unsavedGuard],
                loadComponent: () => import('./features/support/tickets/create/support-new').then((m) => m.SupportNewPage),
            },
            {
                path: 'categories',
                data: { breadcrumb: 'supportCategories', permission: 'support.admin' },
                canActivate: [permissionGuard],
                canDeactivate: [unsavedGuard],
                loadComponent: () => import('./features/support/categories/support-categories').then((m) => m.SupportCategoriesPage),
            },
            {
                path: ':id',
                data: { breadcrumb: 'supportTicketDetails' },
                canDeactivate: [unsavedGuard],
                loadComponent: () => import('./features/support/tickets/detail/support-detail').then((m) => m.SupportDetailPage),
            },
        ],
    },
    {
        path: 'file-storage',
        data: { breadcrumb: 'files' },
        canActivate: [authGuard, destinationGuard(workspaceDestinations.fileStorage)],
        canDeactivate: [unsavedGuard],
        loadComponent: () => import('./features/file-storage/files/file-storage').then((m) => m.FileStoragePage),
    },
    {
        path: 'privacy',
        data: { breadcrumb: 'privacyAndData' },
        canActivate: [authGuard],
        loadComponent: () => import('./features/privacy/privacy').then((m) => m.PrivacyPage),
    },
    { path: 'users/:id', redirectTo: 'administration/users/:id', pathMatch: 'full' },
    { path: 'audit', redirectTo: 'administration/audit-history', pathMatch: 'full' },
    { path: 'operations', redirectTo: 'administration/system-health', pathMatch: 'full' },
    {
        path: 'administration',
        data: { breadcrumb: 'administration' },
        canActivate: [authGuard],
        children: [
            { path: '', pathMatch: 'full', canActivate: [administrationLandingGuard], children: [] },
            {
                path: 'users',
                data: {
                    breadcrumb: 'userManagement',
                    permissions: ['users.read', 'users.manage', 'roles.manage', 'settings.manage'],
                },
                canActivate: [authGuard, permissionGuard],
                children: [
                    {
                        path: '',
                        pathMatch: 'full',
                        data: { breadcrumb: false, section: 'users' },
                        canActivate: [peopleLandingGuard],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/users/users').then((m) => m.UsersPage),
                    },
                    {
                        path: 'invitations',
                        data: { breadcrumb: 'invitations', permission: 'users.manage', section: 'invitations' },
                        canActivate: [permissionGuard],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/users/users').then((m) => m.UsersPage),
                    },
                    {
                        path: 'roles',
                        data: { breadcrumb: 'roles', permission: 'roles.manage', section: 'roles' },
                        canActivate: [permissionGuard],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/users/users').then((m) => m.UsersPage),
                    },
                    {
                        path: 'account-security',
                        data: { breadcrumb: 'security', permission: 'settings.manage', section: 'security' },
                        canActivate: [permissionGuard],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/users/users').then((m) => m.UsersPage),
                    },
                    {
                        path: 'privacy-requests',
                        data: {
                            breadcrumb: 'privacyRequests',
                            permission: 'settings.manage',
                            section: 'privacy',
                        },
                        canActivate: [permissionGuard],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/users/users').then((m) => m.UsersPage),
                    },
                    {
                        path: ':ownerId/files',
                        pathMatch: 'full',
                        redirectTo: ({ params, queryParams }) => inject(Router).createUrlTree(['/administration/users', params['ownerId'], 'file-storage'], { queryParams }),
                    },
                    {
                        path: ':ownerId/file-storage',
                        data: { breadcrumb: 'files', permission: 'settings.manage' },
                        canActivate: [permissionGuard, capabilityGuard('file-storage')],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/file-storage/files/file-storage').then((m) => m.FileStoragePage),
                    },
                    {
                        path: ':id',
                        data: { breadcrumb: 'personDetails', permission: 'users.read' },
                        canActivate: [permissionGuard],
                        canDeactivate: [unsavedGuard],
                        loadComponent: () => import('./features/users/user-detail').then((m) => m.UserDetailPage),
                    },
                ],
            },
            {
                path: 'modules',
                data: { breadcrumb: 'modules', permission: 'settings.manage' },
                canActivate: [authGuard, destinationGuard(administrationDestinations.modules)],
                loadComponent: () => import('./features/modules/modules').then((m) => m.ModulesPage),
            },
            {
                path: 'billing',
                canDeactivate: [unsavedGuard],
                resolve: { customerTranslations, businessTranslations },
                data: { breadcrumb: 'billingSettings', permission: 'settings.manage' },
                canActivate: [authGuard, destinationGuard(administrationDestinations.billing)],
                loadComponent: () => import('./features/billing/billing-settings').then((m) => m.BillingSettingsPage),
            },
            {
                path: 'configuration',
                data: { breadcrumb: 'configuration', permission: 'settings.manage' },
                canActivate: [authGuard, destinationGuard(administrationDestinations.configuration)],
                canDeactivate: [unsavedGuard],
                loadComponent: () => import('./features/configuration/configuration').then((m) => m.ConfigurationPage),
            },
            {
                path: 'file-storage',
                data: { breadcrumb: 'storageSettings', permission: 'settings.manage' },
                canActivate: [authGuard, destinationGuard(administrationDestinations.storage)],
                canDeactivate: [unsavedGuard],
                loadComponent: () => import('./features/file-storage/configuration/storage-settings').then((m) => m.StorageSettingsPage),
            },
            {
                path: 'audit-history',
                data: { breadcrumb: 'auditHistory', permission: 'settings.manage' },
                canActivate: [authGuard, destinationGuard(administrationDestinations.auditHistory)],
                loadComponent: () => import('./features/audit-history/audit').then((m) => m.AuditPage),
            },
            {
                path: 'system-health',
                data: { breadcrumb: 'systemHealth', permissions: ['settings.manage', 'jobs.trigger'] },
                canActivate: [authGuard, destinationGuard(administrationDestinations.operations)],
                loadComponent: () => import('./features/operations/operations').then((m) => m.OperationsPage),
            },
        ],
    },
    {
        path: 'forbidden',
        data: { breadcrumb: 'accessRestricted', forbidden: true },
        canActivate: [authGuard],
        loadComponent: () => import('./features/modules/unavailable').then((m) => m.UnavailablePage),
    },
    {
        path: '**',
        data: { breadcrumb: 'pageNotFound' },
        loadComponent: () => import('./features/modules/unavailable').then((m) => m.UnavailablePage),
    },
];
