using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace TemplateV4.Support.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddTicketReferences : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("""
                ALTER TABLE support.tickets ADD COLUMN "ReferenceNumber" bigint;
                WITH numbered AS (
                    SELECT "Id", row_number() OVER (ORDER BY "CreatedAt", "Id") AS number
                    FROM support.tickets
                )
                UPDATE support.tickets AS ticket
                SET "ReferenceNumber" = numbered.number
                FROM numbered WHERE ticket."Id" = numbered."Id";
                ALTER TABLE support.tickets ALTER COLUMN "ReferenceNumber" SET NOT NULL;
                ALTER TABLE support.tickets ALTER COLUMN "ReferenceNumber" ADD GENERATED BY DEFAULT AS IDENTITY;
                SELECT setval(pg_get_serial_sequence('support.tickets', 'ReferenceNumber'),
                    COALESCE((SELECT max("ReferenceNumber") FROM support.tickets), 0) + 1, false);
                UPDATE support.tickets SET "Priority" = 'Critical' WHERE "Priority" = 'Urgent';
                """);

            migrationBuilder.CreateIndex(
                name: "IX_tickets_ReferenceNumber",
                schema: "support",
                table: "tickets",
                column: "ReferenceNumber",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(
                name: "IX_tickets_ReferenceNumber",
                schema: "support",
                table: "tickets");

            migrationBuilder.DropColumn(
                name: "ReferenceNumber",
                schema: "support",
                table: "tickets");
        }
    }
}
