/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RegistrationSettings } from '../../models/registration-settings';

export interface GetRegistrationSettings$Params {
}

export function getRegistrationSettings(http: HttpClient, rootUrl: string, params?: GetRegistrationSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<RegistrationSettings>> {
  const rb = new RequestBuilder(rootUrl, getRegistrationSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<RegistrationSettings>;
    })
  );
}

getRegistrationSettings.PATH = '/api/v1/auth/registration';
