/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PasskeyOptions } from '../../models/passkey-options';
import { SecurityProof } from '../../models/security-proof';

export interface PasskeyRegistrationOptions$Params {
      body: SecurityProof
}

export function passkeyRegistrationOptions(http: HttpClient, rootUrl: string, params: PasskeyRegistrationOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<PasskeyOptions>> {
  const rb = new RequestBuilder(rootUrl, passkeyRegistrationOptions.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PasskeyOptions>;
    })
  );
}

passkeyRegistrationOptions.PATH = '/api/v1/auth/passkeys/register-options';
