/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SecurityPolicyRequest } from '../../models/security-policy-request';
import { SecuritySettings } from '../../models/security-settings';

export interface SetSecuritySettings$Params {
      body: SecurityPolicyRequest
}

export function setSecuritySettings(http: HttpClient, rootUrl: string, params: SetSecuritySettings$Params, context?: HttpContext): Observable<StrictHttpResponse<SecuritySettings>> {
  const rb = new RequestBuilder(rootUrl, setSecuritySettings.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SecuritySettings>;
    })
  );
}

setSecuritySettings.PATH = '/api/v1/auth/settings/security';
