/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ArchiveCrmRecord } from '../../models/archive-crm-record';
import { CrmRecord } from '../../models/crm-record';

export interface ArchiveCrmRecord$Params {
  organisation: string;
  id: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: ArchiveCrmRecord
}

export function archiveCrmRecord(http: HttpClient, rootUrl: string, params: ArchiveCrmRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<CrmRecord>> {
  const rb = new RequestBuilder(rootUrl, archiveCrmRecord.PATH, 'post');
  if (params) {
    rb.path('organisation', params.organisation, {});
    rb.path('id', params.id, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrmRecord>;
    })
  );
}

archiveCrmRecord.PATH = '/api/v1/auth/organisations/{organisation}/crm/{id}/archive';
