/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MfaEnrollment } from '../../models/mfa-enrollment';
import { SecurityProof } from '../../models/security-proof';

export interface BeginMfaEnrollment$Params {
      body: SecurityProof
}

export function beginMfaEnrollment(http: HttpClient, rootUrl: string, params: BeginMfaEnrollment$Params, context?: HttpContext): Observable<StrictHttpResponse<MfaEnrollment>> {
  const rb = new RequestBuilder(rootUrl, beginMfaEnrollment.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MfaEnrollment>;
    })
  );
}

beginMfaEnrollment.PATH = '/api/v1/auth/mfa/enroll';
