/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccessResponse } from '../../models/access-response';
import { PasskeyCredential } from '../../models/passkey-credential';

export interface CompletePasskeyMfa$Params {
      body: PasskeyCredential
}

export function completePasskeyMfa(http: HttpClient, rootUrl: string, params: CompletePasskeyMfa$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessResponse>> {
  const rb = new RequestBuilder(rootUrl, completePasskeyMfa.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccessResponse>;
    })
  );
}

completePasskeyMfa.PATH = '/api/v1/auth/passkeys/mfa';
