/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { IssuerSettings } from '../../models/issuer-settings';

export interface ConfigureInvoicing$Params {

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: IssuerSettings
}

export function configureInvoicing(http: HttpClient, rootUrl: string, params: ConfigureInvoicing$Params, context?: HttpContext): Observable<StrictHttpResponse<IssuerSettings>> {
  const rb = new RequestBuilder(rootUrl, configureInvoicing.PATH, 'post');
  if (params) {
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<IssuerSettings>;
    })
  );
}

configureInvoicing.PATH = '/api/v1/auth/organisation/invoicing/settings';
