/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrmConfiguration } from '../../models/crm-configuration';

export interface ConfigureCrm$Params {
  organisation: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: CrmConfiguration
}

export function configureCrm(http: HttpClient, rootUrl: string, params: ConfigureCrm$Params, context?: HttpContext): Observable<StrictHttpResponse<CrmConfiguration>> {
  const rb = new RequestBuilder(rootUrl, configureCrm.PATH, 'post');
  if (params) {
    rb.path('organisation', params.organisation, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrmConfiguration>;
    })
  );
}

configureCrm.PATH = '/api/v1/auth/organisations/{organisation}/crm/configuration';
