/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface DownloadPublicFileStorageFile$Params {
  id: string;
  'X-File-Share'?: string;
}

export function downloadPublicFileStorageFile(http: HttpClient, rootUrl: string, params: DownloadPublicFileStorageFile$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, downloadPublicFileStorageFile.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('X-File-Share', params['X-File-Share'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

downloadPublicFileStorageFile.PATH = '/api/v1/auth/file-storage/public/{id}/download';
