/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionAssignee } from '../../models/action-assignee';

export interface FindActionAssignees$Params {
  search?: string;
}

export function findActionAssignees(http: HttpClient, rootUrl: string, params?: FindActionAssignees$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActionAssignee>>> {
  const rb = new RequestBuilder(rootUrl, findActionAssignees.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActionAssignee>>;
    })
  );
}

findActionAssignees.PATH = '/api/v1/auth/action-items/assignees';
