/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommercialBillingSettings } from '../../models/commercial-billing-settings';

export interface GetCommercialBillingSettings$Params {
}

export function getCommercialBillingSettings(http: HttpClient, rootUrl: string, params?: GetCommercialBillingSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<CommercialBillingSettings>> {
  const rb = new RequestBuilder(rootUrl, getCommercialBillingSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommercialBillingSettings>;
    })
  );
}

getCommercialBillingSettings.PATH = '/api/v1/auth/configuration/commercial-billing';
