/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CmsArticle } from '../../models/cms-article';

export interface GetCmsArticle$Params {
  id: string;
}

export function getCmsArticle(http: HttpClient, rootUrl: string, params: GetCmsArticle$Params, context?: HttpContext): Observable<StrictHttpResponse<CmsArticle>> {
  const rb = new RequestBuilder(rootUrl, getCmsArticle.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CmsArticle>;
    })
  );
}

getCmsArticle.PATH = '/api/v1/auth/cms/{id}';
