/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { TicketDetail } from '../../models/ticket-detail';

export interface GetSupportTicket$Params {
  id: string;
  pageNumber?: number;
}

export function getSupportTicket(http: HttpClient, rootUrl: string, params: GetSupportTicket$Params, context?: HttpContext): Observable<StrictHttpResponse<TicketDetail>> {
  const rb = new RequestBuilder(rootUrl, getSupportTicket.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('pageNumber', params.pageNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<TicketDetail>;
    })
  );
}

getSupportTicket.PATH = '/api/v1/auth/support/{id}';
