/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProfileOptions } from '../../models/profile-options';

export interface GetProfileOptions$Params {
}

export function getProfileOptions(http: HttpClient, rootUrl: string, params?: GetProfileOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<ProfileOptions>> {
  const rb = new RequestBuilder(rootUrl, getProfileOptions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProfileOptions>;
    })
  );
}

getProfileOptions.PATH = '/api/v1/auth/profile/options';
