/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AccessCatalog } from '../../models/access-catalog';

export interface GetAccessCatalog$Params {
  pageNumber?: number;
  pageSize?: number;
  search?: string;
  sort?: string;
  direction?: string;
}

export function getAccessCatalog(http: HttpClient, rootUrl: string, params?: GetAccessCatalog$Params, context?: HttpContext): Observable<StrictHttpResponse<AccessCatalog>> {
  const rb = new RequestBuilder(rootUrl, getAccessCatalog.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('search', params.search, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AccessCatalog>;
    })
  );
}

getAccessCatalog.PATH = '/api/v1/roles';
