/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UpdateSummary } from '../../models/update-summary';

export interface GetReleaseUpdates$Params {
}

export function getReleaseUpdates(http: HttpClient, rootUrl: string, params?: GetReleaseUpdates$Params, context?: HttpContext): Observable<StrictHttpResponse<UpdateSummary>> {
  const rb = new RequestBuilder(rootUrl, getReleaseUpdates.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UpdateSummary>;
    })
  );
}

getReleaseUpdates.PATH = '/api/v1/auth/updates';
