/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrmConfiguration } from '../../models/crm-configuration';

export interface GetCrmConfiguration$Params {
}

export function getCrmConfiguration(http: HttpClient, rootUrl: string, params?: GetCrmConfiguration$Params, context?: HttpContext): Observable<StrictHttpResponse<CrmConfiguration>> {
  const rb = new RequestBuilder(rootUrl, getCrmConfiguration.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CrmConfiguration>;
    })
  );
}

getCrmConfiguration.PATH = '/api/v1/auth/organisation/crm/configuration';
