/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { UserAccessDetail } from '../../models/user-access-detail';

export interface GetUserAccess$Params {
  id: string;
}

export function getUserAccess(http: HttpClient, rootUrl: string, params: GetUserAccess$Params, context?: HttpContext): Observable<StrictHttpResponse<UserAccessDetail>> {
  const rb = new RequestBuilder(rootUrl, getUserAccess.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<UserAccessDetail>;
    })
  );
}

getUserAccess.PATH = '/api/v1/users/{id}';
