/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebPushStatus } from '../../models/web-push-status';

export interface GetWebPushStatus$Params {
}

export function getWebPushStatus(http: HttpClient, rootUrl: string, params?: GetWebPushStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<WebPushStatus>> {
  const rb = new RequestBuilder(rootUrl, getWebPushStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebPushStatus>;
    })
  );
}

getWebPushStatus.PATH = '/api/v1/auth/notifications/push';
