/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SupportOptions } from '../../models/support-options';

export interface GetSupportOptions$Params {
  search?: string;
}

export function getSupportOptions(http: HttpClient, rootUrl: string, params?: GetSupportOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportOptions>> {
  const rb = new RequestBuilder(rootUrl, getSupportOptions.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupportOptions>;
    })
  );
}

getSupportOptions.PATH = '/api/v1/auth/support/options';
