/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ActionQueue } from '../../models/action-queue';

export interface GetActionItemQueues$Params {
}

export function getActionItemQueues(http: HttpClient, rootUrl: string, params?: GetActionItemQueues$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ActionQueue>>> {
  const rb = new RequestBuilder(rootUrl, getActionItemQueues.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ActionQueue>>;
    })
  );
}

getActionItemQueues.PATH = '/api/v1/auth/action-items/queues';
