/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PublicAppearance } from '../../models/public-appearance';

export interface GetPublicAppearance$Params {
}

export function getPublicAppearance(http: HttpClient, rootUrl: string, params?: GetPublicAppearance$Params, context?: HttpContext): Observable<StrictHttpResponse<PublicAppearance>> {
  const rb = new RequestBuilder(rootUrl, getPublicAppearance.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PublicAppearance>;
    })
  );
}

getPublicAppearance.PATH = '/api/v1/auth/appearance';
