/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PrivacyStatus } from '../../models/privacy-status';

export interface GetPrivacyStatus$Params {
}

export function getPrivacyStatus(http: HttpClient, rootUrl: string, params?: GetPrivacyStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<PrivacyStatus>> {
  const rb = new RequestBuilder(rootUrl, getPrivacyStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PrivacyStatus>;
    })
  );
}

getPrivacyStatus.PATH = '/api/v1/auth/privacy';
