/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OperationsOverview } from '../../models/operations-overview';

export interface GetOperationsOverview$Params {
}

export function getOperationsOverview(http: HttpClient, rootUrl: string, params?: GetOperationsOverview$Params, context?: HttpContext): Observable<StrictHttpResponse<OperationsOverview>> {
  const rb = new RequestBuilder(rootUrl, getOperationsOverview.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OperationsOverview>;
    })
  );
}

getOperationsOverview.PATH = '/api/v1/auth/operations/overview';
