/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BillingSummary } from '../../models/billing-summary';

export interface GetCustomerBilling$Params {
  customer: string;
}

export function getCustomerBilling(http: HttpClient, rootUrl: string, params: GetCustomerBilling$Params, context?: HttpContext): Observable<StrictHttpResponse<BillingSummary>> {
  const rb = new RequestBuilder(rootUrl, getCustomerBilling.PATH, 'get');
  if (params) {
    rb.path('customer', params.customer, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BillingSummary>;
    })
  );
}

getCustomerBilling.PATH = '/api/v1/auth/customers/{customer}/billing';
