/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileStorageModuleSettings } from '../../models/file-storage-module-settings';

export interface GetFileStorageModuleSettings$Params {
}

export function getFileStorageModuleSettings(http: HttpClient, rootUrl: string, params?: GetFileStorageModuleSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<FileStorageModuleSettings>> {
  const rb = new RequestBuilder(rootUrl, getFileStorageModuleSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileStorageModuleSettings>;
    })
  );
}

getFileStorageModuleSettings.PATH = '/api/v1/auth/administration/modules/file-storage/settings';
