/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommercialDetail } from '../../models/commercial-detail';

export interface GetCommercialDocument$Params {
  organisation: string;
  id: string;
}

export function getCommercialDocument(http: HttpClient, rootUrl: string, params: GetCommercialDocument$Params, context?: HttpContext): Observable<StrictHttpResponse<CommercialDetail>> {
  const rb = new RequestBuilder(rootUrl, getCommercialDocument.PATH, 'get');
  if (params) {
    rb.path('organisation', params.organisation, {});
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommercialDetail>;
    })
  );
}

getCommercialDocument.PATH = '/api/v1/auth/organisations/{organisation}/invoicing/{id}';
