/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileStorageSettings } from '../../models/file-storage-settings';

export interface GetMyFilesStorageSettings$Params {
}

export function getMyFilesStorageSettings(http: HttpClient, rootUrl: string, params?: GetMyFilesStorageSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<FileStorageSettings>> {
  const rb = new RequestBuilder(rootUrl, getMyFilesStorageSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileStorageSettings>;
    })
  );
}

getMyFilesStorageSettings.PATH = '/api/v1/auth/my-files/admin/settings';
