/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileItem } from '../../models/file-item';

export interface GetPublicMyFile$Params {
  id: string;
  'X-File-Share'?: string;
}

export function getPublicMyFile(http: HttpClient, rootUrl: string, params: GetPublicMyFile$Params, context?: HttpContext): Observable<StrictHttpResponse<FileItem>> {
  const rb = new RequestBuilder(rootUrl, getPublicMyFile.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('X-File-Share', params['X-File-Share'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileItem>;
    })
  );
}

getPublicMyFile.PATH = '/api/v1/auth/my-files/public/{id}';
