/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { BillingSettings } from '../../models/billing-settings';

export interface GetBillingSettings$Params {
}

export function getBillingSettings(http: HttpClient, rootUrl: string, params?: GetBillingSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<BillingSettings>> {
  const rb = new RequestBuilder(rootUrl, getBillingSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<BillingSettings>;
    })
  );
}

getBillingSettings.PATH = '/api/v1/auth/configuration/billing';
