/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { AdminBootstrapStatus } from '../../models/admin-bootstrap-status';

export interface GetAdminBootstrapStatus$Params {
}

export function getAdminBootstrapStatus(http: HttpClient, rootUrl: string, params?: GetAdminBootstrapStatus$Params, context?: HttpContext): Observable<StrictHttpResponse<AdminBootstrapStatus>> {
  const rb = new RequestBuilder(rootUrl, getAdminBootstrapStatus.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<AdminBootstrapStatus>;
    })
  );
}

getAdminBootstrapStatus.PATH = '/api/v1/bootstrap/status';
