/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfBlogSummary } from '../../models/page-of-blog-summary';

export interface GetPublicBlog$Params {
  pageNumber?: number;
}

export function getPublicBlog(http: HttpClient, rootUrl: string, params?: GetPublicBlog$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfBlogSummary>> {
  const rb = new RequestBuilder(rootUrl, getPublicBlog.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfBlogSummary>;
    })
  );
}

getPublicBlog.PATH = '/api/v1/website/cms/blog';
