/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PaymentMethodStatus } from '../../models/payment-method-status';

export interface GetPaymentMethods$Params {
}

export function getPaymentMethods(http: HttpClient, rootUrl: string, params?: GetPaymentMethods$Params, context?: HttpContext): Observable<StrictHttpResponse<PaymentMethodStatus>> {
  const rb = new RequestBuilder(rootUrl, getPaymentMethods.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PaymentMethodStatus>;
    })
  );
}

getPaymentMethods.PATH = '/api/v1/auth/configuration/payment-methods';
