/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentAccessOptions } from '../../models/content-access-options';

export interface GetContentAccessOptions$Params {
}

export function getContentAccessOptions(http: HttpClient, rootUrl: string, params?: GetContentAccessOptions$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentAccessOptions>> {
  const rb = new RequestBuilder(rootUrl, getContentAccessOptions.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentAccessOptions>;
    })
  );
}

getContentAccessOptions.PATH = '/api/v1/auth/cms/collections/access-options';
