/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { DashboardCardData } from '../../models/dashboard-card-data';

export interface GetDashboardCard$Params {
  DefinitionId: string;
  Metric?: string;
  Filter?: string;
  Period?: string;
  Limit?: number;
}

export function getDashboardCard(http: HttpClient, rootUrl: string, params: GetDashboardCard$Params, context?: HttpContext): Observable<StrictHttpResponse<DashboardCardData>> {
  const rb = new RequestBuilder(rootUrl, getDashboardCard.PATH, 'get');
  if (params) {
    rb.query('DefinitionId', params.DefinitionId, {});
    rb.query('Metric', params.Metric, {});
    rb.query('Filter', params.Filter, {});
    rb.query('Period', params.Period, {});
    rb.query('Limit', params.Limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<DashboardCardData>;
    })
  );
}

getDashboardCard.PATH = '/api/v1/auth/dashboards/card';
