/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { LandingSection } from '../../models/landing-section';

export interface GetPublicCmsSections$Params {
}

export function getPublicCmsSections(http: HttpClient, rootUrl: string, params?: GetPublicCmsSections$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<LandingSection>>> {
  const rb = new RequestBuilder(rootUrl, getPublicCmsSections.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<LandingSection>>;
    })
  );
}

getPublicCmsSections.PATH = '/api/v1/website/cms/sections';
