/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommercialBillingSummary } from '../../models/commercial-billing-summary';

export interface GetCommercialBilling$Params {
}

export function getCommercialBilling(http: HttpClient, rootUrl: string, params?: GetCommercialBilling$Params, context?: HttpContext): Observable<StrictHttpResponse<CommercialBillingSummary>> {
  const rb = new RequestBuilder(rootUrl, getCommercialBilling.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommercialBillingSummary>;
    })
  );
}

getCommercialBilling.PATH = '/api/v1/auth/commercial-billing';
