/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebsiteSettings } from '../../models/website-settings';

export interface GetWebsiteSettings$Params {
}

export function getWebsiteSettings(http: HttpClient, rootUrl: string, params?: GetWebsiteSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<WebsiteSettings>> {
  const rb = new RequestBuilder(rootUrl, getWebsiteSettings.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebsiteSettings>;
    })
  );
}

getWebsiteSettings.PATH = '/api/v1/auth/website';
