/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfCustomerMember } from '../../models/page-of-customer-member';

export interface GetOrganizationMembers$Params {
  customer: string;
  pageNumber?: number;
  pageSize?: number;
  sort?: string;
  direction?: string;
}

export function getOrganizationMembers(http: HttpClient, rootUrl: string, params: GetOrganizationMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfCustomerMember>> {
  const rb = new RequestBuilder(rootUrl, getOrganizationMembers.PATH, 'get');
  if (params) {
    rb.path('customer', params.customer, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfCustomerMember>;
    })
  );
}

getOrganizationMembers.PATH = '/api/v1/auth/customers/{customer}/members';
