/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationSummary } from '../../models/notification-summary';

export interface GetNotificationSummary$Params {
}

export function getNotificationSummary(http: HttpClient, rootUrl: string, params?: GetNotificationSummary$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationSummary>> {
  const rb = new RequestBuilder(rootUrl, getNotificationSummary.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationSummary>;
    })
  );
}

getNotificationSummary.PATH = '/api/v1/auth/notifications/summary';
