/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommercialDocument } from '../../models/commercial-document';

export interface InvoiceAcceptedQuotation$Params {
  id: string;
  idempotencyKey: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
}

export function invoiceAcceptedQuotation(http: HttpClient, rootUrl: string, params: InvoiceAcceptedQuotation$Params, context?: HttpContext): Observable<StrictHttpResponse<CommercialDocument>> {
  const rb = new RequestBuilder(rootUrl, invoiceAcceptedQuotation.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('idempotencyKey', params.idempotencyKey, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommercialDocument>;
    })
  );
}

invoiceAcceptedQuotation.PATH = '/api/v1/auth/organisation/invoicing/{id}/invoice';
