/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ModuleActivation } from '../../models/module-activation';

export interface ListModuleActivations$Params {
}

export function listModuleActivations(http: HttpClient, rootUrl: string, params?: ListModuleActivations$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ModuleActivation>>> {
  const rb = new RequestBuilder(rootUrl, listModuleActivations.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ModuleActivation>>;
    })
  );
}

listModuleActivations.PATH = '/api/v1/auth/administration/modules/activation';
