/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InvoicePdfVersion } from '../../models/invoice-pdf-version';

export interface ListInvoicePdfVersions$Params {
  id: string;
}

export function listInvoicePdfVersions(http: HttpClient, rootUrl: string, params: ListInvoicePdfVersions$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<InvoicePdfVersion>>> {
  const rb = new RequestBuilder(rootUrl, listInvoicePdfVersions.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<InvoicePdfVersion>>;
    })
  );
}

listInvoicePdfVersions.PATH = '/api/v1/auth/organisation/invoicing/{id}/pdf-versions';
