/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfCommercialDocument } from '../../models/page-of-commercial-document';

export interface ListCommercialDocuments$Params {
  pageNumber?: number;
  pageSize?: number;
  search?: string;
  sort?: string;
  direction?: string;
  group?: string;
}

export function listCommercialDocuments(http: HttpClient, rootUrl: string, params?: ListCommercialDocuments$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfCommercialDocument>> {
  const rb = new RequestBuilder(rootUrl, listCommercialDocuments.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('search', params.search, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
    rb.query('group', params.group, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfCommercialDocument>;
    })
  );
}

listCommercialDocuments.PATH = '/api/v1/auth/organisation/invoicing';
