/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfDeletionItem } from '../../models/page-of-deletion-item';

export interface ListDeletionRequests$Params {
  pageNumber?: number;
}

export function listDeletionRequests(http: HttpClient, rootUrl: string, params?: ListDeletionRequests$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfDeletionItem>> {
  const rb = new RequestBuilder(rootUrl, listDeletionRequests.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfDeletionItem>;
    })
  );
}

listDeletionRequests.PATH = '/api/v1/auth/privacy/requests';
