/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfInvitationItem } from '../../models/page-of-invitation-item';

export interface ListInvitations$Params {
  pageNumber?: number;
  search?: string;
  state?: string;
}

export function listInvitations(http: HttpClient, rootUrl: string, params?: ListInvitations$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfInvitationItem>> {
  const rb = new RequestBuilder(rootUrl, listInvitations.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('search', params.search, {});
    rb.query('state', params.state, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfInvitationItem>;
    })
  );
}

listInvitations.PATH = '/api/v1/auth/invitations';
