/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SessionAuditPage } from '../../models/session-audit-page';

export interface ListSessionAudit$Params {
  id: string;
  PageNumber?: number;
  PageSize?: number;
  Sort?: string;
  Direction?: string;
}

export function listSessionAudit(http: HttpClient, rootUrl: string, params: ListSessionAudit$Params, context?: HttpContext): Observable<StrictHttpResponse<SessionAuditPage>> {
  const rb = new RequestBuilder(rootUrl, listSessionAudit.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Sort', params.Sort, {});
    rb.query('Direction', params.Direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SessionAuditPage>;
    })
  );
}

listSessionAudit.PATH = '/api/v1/auth/sessions/{id}/audit';
