/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ApiKeyPage } from '../../models/api-key-page';

export interface ListApiKeys$Params {
  Search?: string;
  PageNumber?: number;
  PageSize?: number;
  Sort?: string;
  Direction?: string;
}

export function listApiKeys(http: HttpClient, rootUrl: string, params?: ListApiKeys$Params, context?: HttpContext): Observable<StrictHttpResponse<ApiKeyPage>> {
  const rb = new RequestBuilder(rootUrl, listApiKeys.PATH, 'get');
  if (params) {
    rb.query('Search', params.Search, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Sort', params.Sort, {});
    rb.query('Direction', params.Direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ApiKeyPage>;
    })
  );
}

listApiKeys.PATH = '/api/v1/auth/administration/api-keys';
