/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { NotificationPage } from '../../models/notification-page';

export interface ListNotifications$Params {
  pageNumber?: number;
  pageSize?: number;
  unreadOnly?: boolean;
  sort?: string;
  direction?: string;
}

export function listNotifications(http: HttpClient, rootUrl: string, params?: ListNotifications$Params, context?: HttpContext): Observable<StrictHttpResponse<NotificationPage>> {
  const rb = new RequestBuilder(rootUrl, listNotifications.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('unreadOnly', params.unreadOnly, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<NotificationPage>;
    })
  );
}

listNotifications.PATH = '/api/v1/auth/notifications';
