/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CrmRecordKind } from '../../models/crm-record-kind';
import { PageOfCrmRecord } from '../../models/page-of-crm-record';

export interface ListCrmRecords$Params {
  kind?: CrmRecordKind;
  search?: string;
  archived?: boolean;
  pageNumber?: number;
  pageSize?: number;
  sort?: string;
  direction?: string;
}

export function listCrmRecords(http: HttpClient, rootUrl: string, params?: ListCrmRecords$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfCrmRecord>> {
  const rb = new RequestBuilder(rootUrl, listCrmRecords.PATH, 'get');
  if (params) {
    rb.query('kind', params.kind, {});
    rb.query('search', params.search, {});
    rb.query('archived', params.archived, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfCrmRecord>;
    })
  );
}

listCrmRecords.PATH = '/api/v1/auth/organisation/crm';
