/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentCollection } from '../../models/content-collection';

export interface ListContentCollections$Params {
}

export function listContentCollections(http: HttpClient, rootUrl: string, params?: ListContentCollections$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<ContentCollection>>> {
  const rb = new RequestBuilder(rootUrl, listContentCollections.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<ContentCollection>>;
    })
  );
}

listContentCollections.PATH = '/api/v1/auth/cms/collections';
