/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FilePage } from '../../models/file-page';

export interface ListFiles$Params {
  pageNumber?: number;
  pageSize?: number;
  search?: string;
  sort?: string;
  direction?: string;
}

export function listFiles(http: HttpClient, rootUrl: string, params?: ListFiles$Params, context?: HttpContext): Observable<StrictHttpResponse<FilePage>> {
  const rb = new RequestBuilder(rootUrl, listFiles.PATH, 'get');
  if (params) {
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('search', params.search, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FilePage>;
    })
  );
}

listFiles.PATH = '/api/v1/auth/files';
