/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { RuntimeModule } from '../../models/runtime-module';

export interface ListRuntimeModules$Params {
}

export function listRuntimeModules(http: HttpClient, rootUrl: string, params?: ListRuntimeModules$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<RuntimeModule>>> {
  const rb = new RequestBuilder(rootUrl, listRuntimeModules.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<RuntimeModule>>;
    })
  );
}

listRuntimeModules.PATH = '/api/v1/auth/administration/modules';
