/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfContentItemSummary } from '../../models/page-of-content-item-summary';

export interface ListContentItems$Params {
  key: string;
  PageNumber?: number;
  PageSize?: number;
  Search?: string;
  Sort?: string;
  Direction?: string;
  State?: string;
  Filter?: string;
}

export function listContentItems(http: HttpClient, rootUrl: string, params: ListContentItems$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfContentItemSummary>> {
  const rb = new RequestBuilder(rootUrl, listContentItems.PATH, 'get');
  if (params) {
    rb.path('key', params.key, {});
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Search', params.Search, {});
    rb.query('Sort', params.Sort, {});
    rb.query('Direction', params.Direction, {});
    rb.query('State', params.State, {});
    rb.query('Filter', params.Filter, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfContentItemSummary>;
    })
  );
}

listContentItems.PATH = '/api/v1/auth/cms/collections/{key}/items';
