/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfCmsArticleSummary } from '../../models/page-of-cms-article-summary';

export interface ListCmsArticles$Params {
  search?: string;
  status?: string;
  pageNumber?: number;
  pageSize?: number;
  sort?: string;
  direction?: string;
}

export function listCmsArticles(http: HttpClient, rootUrl: string, params?: ListCmsArticles$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfCmsArticleSummary>> {
  const rb = new RequestBuilder(rootUrl, listCmsArticles.PATH, 'get');
  if (params) {
    rb.query('search', params.search, {});
    rb.query('status', params.status, {});
    rb.query('pageNumber', params.pageNumber, {});
    rb.query('pageSize', params.pageSize, {});
    rb.query('sort', params.sort, {});
    rb.query('direction', params.direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfCmsArticleSummary>;
    })
  );
}

listCmsArticles.PATH = '/api/v1/auth/cms';
