/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileShareItem } from '../../models/file-share-item';

export interface ListFileStorageShares$Params {
  id: string;
}

export function listFileStorageShares(http: HttpClient, rootUrl: string, params: ListFileStorageShares$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<FileShareItem>>> {
  const rb = new RequestBuilder(rootUrl, listFileStorageShares.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<FileShareItem>>;
    })
  );
}

listFileStorageShares.PATH = '/api/v1/auth/file-storage/{id}/shares';
