/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageOfAuditItem } from '../../models/page-of-audit-item';

export interface ListAuditHistory$Params {
  PageNumber?: number;
  PageSize?: number;
  Action?: string;
  ActorId?: string;
  SubjectId?: string;
  From?: string;
  Until?: string;
  Sort?: string;
  Direction?: string;
}

export function listAuditHistory(http: HttpClient, rootUrl: string, params?: ListAuditHistory$Params, context?: HttpContext): Observable<StrictHttpResponse<PageOfAuditItem>> {
  const rb = new RequestBuilder(rootUrl, listAuditHistory.PATH, 'get');
  if (params) {
    rb.query('PageNumber', params.PageNumber, {});
    rb.query('PageSize', params.PageSize, {});
    rb.query('Action', params.Action, {});
    rb.query('ActorId', params.ActorId, {});
    rb.query('SubjectId', params.SubjectId, {});
    rb.query('From', params.From, {});
    rb.query('Until', params.Until, {});
    rb.query('Sort', params.Sort, {});
    rb.query('Direction', params.Direction, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PageOfAuditItem>;
    })
  );
}

listAuditHistory.PATH = '/api/v1/auth/audit';
