/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommercialAction } from '../../models/commercial-action';
import { FinancialEntry } from '../../models/financial-entry';

export interface RefundCommercialInvoice$Params {
  organisation: string;
  id: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: CommercialAction
}

export function refundCommercialInvoice(http: HttpClient, rootUrl: string, params: RefundCommercialInvoice$Params, context?: HttpContext): Observable<StrictHttpResponse<FinancialEntry>> {
  const rb = new RequestBuilder(rootUrl, refundCommercialInvoice.PATH, 'post');
  if (params) {
    rb.path('organisation', params.organisation, {});
    rb.path('id', params.id, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FinancialEntry>;
    })
  );
}

refundCommercialInvoice.PATH = '/api/v1/auth/organisations/{organisation}/invoicing/{id}/refund';
