/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface RetryBackgroundJobRun$Params {
  id: string;
  runId: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
}

export function retryBackgroundJobRun(http: HttpClient, rootUrl: string, params: RetryBackgroundJobRun$Params, context?: HttpContext): Observable<StrictHttpResponse<void>> {
  const rb = new RequestBuilder(rootUrl, retryBackgroundJobRun.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.path('runId', params.runId, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
  }

  return http.request(
    rb.build({ responseType: 'text', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: undefined }) as StrictHttpResponse<void>;
    })
  );
}

retryBackgroundJobRun.PATH = '/api/v1/auth/administration/background-jobs/{id}/runs/{runId}/retry';
