/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileStorageModuleSettings } from '../../models/file-storage-module-settings';
import { SaveFileStorageModuleSettings } from '../../models/save-file-storage-module-settings';

export interface SaveFileStorageModuleSettings$Params {

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: SaveFileStorageModuleSettings
}

export function saveFileStorageModuleSettings(http: HttpClient, rootUrl: string, params: SaveFileStorageModuleSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<FileStorageModuleSettings>> {
  const rb = new RequestBuilder(rootUrl, saveFileStorageModuleSettings.PATH, 'post');
  if (params) {
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileStorageModuleSettings>;
    })
  );
}

saveFileStorageModuleSettings.PATH = '/api/v1/auth/administration/modules/file-storage/settings';
