/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ContentItem } from '../../models/content-item';
import { SaveContentItem } from '../../models/save-content-item';

export interface SaveContentItem$Params {
  key: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: SaveContentItem
}

export function saveContentItem(http: HttpClient, rootUrl: string, params: SaveContentItem$Params, context?: HttpContext): Observable<StrictHttpResponse<ContentItem>> {
  const rb = new RequestBuilder(rootUrl, saveContentItem.PATH, 'post');
  if (params) {
    rb.path('key', params.key, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ContentItem>;
    })
  );
}

saveContentItem.PATH = '/api/v1/auth/cms/collections/{key}/items';
