/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { SaveSupportModuleSettings } from '../../models/save-support-module-settings';
import { SupportModuleSettings } from '../../models/support-module-settings';

export interface SaveSupportModuleSettings$Params {

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: SaveSupportModuleSettings
}

export function saveSupportModuleSettings(http: HttpClient, rootUrl: string, params: SaveSupportModuleSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<SupportModuleSettings>> {
  const rb = new RequestBuilder(rootUrl, saveSupportModuleSettings.PATH, 'post');
  if (params) {
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SupportModuleSettings>;
    })
  );
}

saveSupportModuleSettings.PATH = '/api/v1/auth/administration/modules/support/settings';
