/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MyFilesModuleSettings } from '../../models/my-files-module-settings';
import { SaveMyFilesModuleSettings } from '../../models/save-my-files-module-settings';

export interface SaveMyFilesModuleSettings$Params {

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: SaveMyFilesModuleSettings
}

export function saveMyFilesModuleSettings(http: HttpClient, rootUrl: string, params: SaveMyFilesModuleSettings$Params, context?: HttpContext): Observable<StrictHttpResponse<MyFilesModuleSettings>> {
  const rb = new RequestBuilder(rootUrl, saveMyFilesModuleSettings.PATH, 'post');
  if (params) {
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MyFilesModuleSettings>;
    })
  );
}

saveMyFilesModuleSettings.PATH = '/api/v1/auth/administration/modules/my-files/settings';
