/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { FileShareItem } from '../../models/file-share-item';
import { FileShareRequest } from '../../models/file-share-request';

export interface ShareMyFile$Params {
  id: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
      body: FileShareRequest
}

export function shareMyFile(http: HttpClient, rootUrl: string, params: ShareMyFile$Params, context?: HttpContext): Observable<StrictHttpResponse<FileShareItem>> {
  const rb = new RequestBuilder(rootUrl, shareMyFile.PATH, 'post');
  if (params) {
    rb.path('id', params.id, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<FileShareItem>;
    })
  );
}

shareMyFile.PATH = '/api/v1/auth/my-files/{id}/shares';
