/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CustomerInfo } from '../../models/customer-info';

export interface UploadOrganisationLogo$Params {
  version: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
}

export function uploadOrganisationLogo(http: HttpClient, rootUrl: string, params: UploadOrganisationLogo$Params, context?: HttpContext): Observable<StrictHttpResponse<CustomerInfo>> {
  const rb = new RequestBuilder(rootUrl, uploadOrganisationLogo.PATH, 'post');
  if (params) {
    rb.query('version', params.version, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CustomerInfo>;
    })
  );
}

uploadOrganisationLogo.PATH = '/api/v1/auth/organisation/logo';
