/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { WebsiteImage } from '../../models/website-image';

export interface UploadWebsiteImage$Params {

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
}

export function uploadWebsiteImage(http: HttpClient, rootUrl: string, params: UploadWebsiteImage$Params, context?: HttpContext): Observable<StrictHttpResponse<WebsiteImage>> {
  const rb = new RequestBuilder(rootUrl, uploadWebsiteImage.PATH, 'post');
  if (params) {
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<WebsiteImage>;
    })
  );
}

uploadWebsiteImage.PATH = '/api/v1/auth/website-images';
