/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { OrganisationAttachment } from '../../models/organisation-attachment';

export interface UploadOrganisationAttachment$Params {
  organisation: string;
  name: string;

/**
 * Anonymous-bound antiforgery token returned by GET /api/v1/auth/csrf. The browser must also send an exact allowed Origin.
 */
  'X-CSRF-TOKEN': string;
}

export function uploadOrganisationAttachment(http: HttpClient, rootUrl: string, params: UploadOrganisationAttachment$Params, context?: HttpContext): Observable<StrictHttpResponse<OrganisationAttachment>> {
  const rb = new RequestBuilder(rootUrl, uploadOrganisationAttachment.PATH, 'post');
  if (params) {
    rb.path('organisation', params.organisation, {});
    rb.query('name', params.name, {});
    rb.header('X-CSRF-TOKEN', params['X-CSRF-TOKEN'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<OrganisationAttachment>;
    })
  );
}

uploadOrganisationAttachment.PATH = '/api/v1/auth/organisations/{organisation}/attachments/upload';
