// Generated by tools/framework.mjs module-ids. Do not edit.
export type ModuleId =
  | 'audit-history'
  | 'audit-recording'
  | 'billing'
  | 'delivery'
  | 'identity'
  | 'maintenance'
  | 'my-files'
  | 'operations'
  | 'organizations'
  | 'support';
export type CapabilityId =
  | 'audit-history'
  | 'audit-recording'
  | 'billing'
  | 'delivery'
  | 'identity'
  | 'maintenance'
  | 'my-files'
  | 'operations'
  | 'organization-files'
  | 'organizations'
  | 'support';
