// Generated by tools/framework.mjs module-ids. Do not edit.
export type ModuleId =
  | 'audit-history'
  | 'audit-recording'
  | 'billing'
  | 'cms'
  | 'crm'
  | 'delivery'
  | 'file-storage'
  | 'identity'
  | 'invoicing'
  | 'maintenance'
  | 'organisations'
  | 'support';
export type CapabilityId =
  | 'audit-history'
  | 'audit-recording'
  | 'billing'
  | 'cms'
  | 'crm'
  | 'crm-files'
  | 'delivery'
  | 'file-storage'
  | 'identity'
  | 'invoicing'
  | 'invoicing-files'
  | 'maintenance'
  | 'organisation-files'
  | 'organisations'
  | 'support'
  | 'support-enquiries'
  | 'support-tickets';
export const runtimeConfigurableModuleIds = [
  'cms',
  'crm',
  'file-storage',
  'invoicing',
  'support',
] as const satisfies readonly ModuleId[];
