<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup><OutputType>Library</OutputType><IsPackable>true</IsPackable><Version>0.2.0</Version></PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Infrastructure/TemplateV4.CommercialBilling.Infrastructure.csproj" />
    <ProjectReference Include="../../../../src/TemplateV4.Infrastructure/TemplateV4.Infrastructure.csproj" />
    <Using Include="TemplateV4.SharedKernel" />
  </ItemGroup>
</Project>
