import fs from 'node:fs';
import path from 'node:path';

export function resolveModules(definitions, overrides = {}) {
  if (!Array.isArray(definitions) || definitions.length === 0) throw new Error('Empty module catalog.');
  const known = new Map();
  for (const definition of definitions) {
    if (!definition || !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(definition.id) || typeof definition.required !== 'boolean' ||
        typeof definition.enabledByDefault !== 'boolean' || !Array.isArray(definition.dependencies) ||
        definition.dependencies.some(x => typeof x !== 'string')) throw new Error('Invalid module descriptor.');
    if (known.has(definition.id)) throw new Error(`Duplicate module ${definition.id}.`);
    if (definition.category !== undefined && (!['core', 'foundation', 'private'].includes(definition.category) ||
        (definition.category === 'core' && definition.runtimeConfigurable) || (definition.category === 'private' && definition.required)))
      throw new Error('Invalid module category or lifecycle.');
    known.set(definition.id, definition);
  }
  for (const [id, value] of Object.entries(overrides)) {
    if (!known.has(id)) throw new Error(`Unknown module ${id}.`);
    if (typeof value !== 'boolean') throw new Error(`Module ${id} must be a boolean.`);
  }
  const visited = new Set();
  const visiting = new Set();
  function visit(id) {
    if (visited.has(id)) return;
    if (visiting.has(id)) throw new Error(`Module dependency cycle at ${id}.`);
    visiting.add(id);
    for (const dependency of known.get(id).dependencies) {
      if (!known.has(dependency)) throw new Error(`Unknown dependency ${dependency}.`);
      visit(dependency);
    }
    visiting.delete(id);
    visited.add(id);
  }
  for (const id of known.keys()) visit(id);
  const capabilities = new Map();
  for (const d of definitions) {
    if (d.runtimeConfigurable !== undefined && typeof d.runtimeConfigurable !== 'boolean') throw new Error('Invalid runtime switch.');
    if (d.required && d.runtimeConfigurable) throw new Error('Required modules cannot have runtime switches.');
    for (const c of [{ id: d.id, requires: d.dependencies, featureFlag: d.featureFlag }, ...(d.capabilities ?? []).map(c => ({ ...c, requires: [d.id, ...c.requires] }))]) {
      if (!/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(c.id) || !Array.isArray(c.requires) || c.requires.some(x => typeof x !== 'string') ||
          (c.featureFlag !== undefined && c.featureFlag !== null && !/^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/.test(c.featureFlag)) || capabilities.has(c.id)) throw new Error('Invalid or duplicate capability.');
      capabilities.set(c.id, c);
    }
  }
  visited.clear(); visiting.clear();
  function visitCapability(id) {
    if (visited.has(id)) return;
    if (!capabilities.has(id)) throw new Error(`Unknown capability ${id}.`);
    if (visiting.has(id)) throw new Error(`Capability cycle at ${id}.`);
    visiting.add(id);
    for (const dependency of capabilities.get(id).requires) visitCapability(dependency);
    visiting.delete(id); visited.add(id);
  }
  for (const id of capabilities.keys()) visitCapability(id);
  const enabled = Object.fromEntries(definitions.map(x => [x.id, Object.hasOwn(overrides, x.id) ? overrides[x.id] : x.enabledByDefault]));
  for (const definition of definitions) {
    if (definition.required && !enabled[definition.id]) throw new Error(`Required module ${definition.id} cannot be disabled.`);
    if (enabled[definition.id]) for (const dependency of definition.dependencies)
      if (!enabled[dependency]) throw new Error(`Module ${definition.id} requires ${dependency}.`);
  }
  return enabled;
}

export function generateModuleIds(root, manifest, check = false) {
  const definitions = JSON.parse(fs.readFileSync(path.join(root, manifest.moduleCatalog), 'utf8'));
  resolveModules(definitions);
  const modules = definitions.map(x => x.id).sort();
  const capabilities = definitions.flatMap(x => [x.id, ...(x.capabilities ?? []).map(c => c.id)]).sort();
  const identifier = id => id.split('-').map(x => x[0].toUpperCase() + x.slice(1)).join('');
  const constants = (name, ids) => {
    if (new Set(ids.map(identifier)).size !== ids.length || ids.some(x => /^[0-9]/.test(identifier(x)))) throw new Error('Module identifiers collide or cannot be generated.');
    return `public static class ${name}\n{\n${ids.map(id => `    public const string ${identifier(id)} = "${id}";`).join('\n')}\n}\n`;
  };
  const outputs = {
    [`${manifest.projects.Application}/Modules/ModuleIds.g.cs`]: '// <auto-generated />\nnamespace TemplateV4.Application.Modules;\n\n' + constants('ModuleIds', modules) + '\n' + constants('CapabilityIds', capabilities),
    [`${manifest.projects.Web}/src/app/core/capability-ids.ts`]: '// Generated by tools/framework.mjs module-ids. Do not edit.\n' +
      `export type ModuleId =\n${modules.map(id => `  | '${id}'`).join('\n')};\n` +
      `export type CapabilityId =\n${capabilities.map(id => `  | '${id}'`).join('\n')};\n`,
  };
  for (const [relative, content] of Object.entries(outputs)) {
    const target = path.join(root, relative);
    if (check) {
      if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8').replaceAll('\r\n', '\n') !== content) throw new Error(`Generated module identifiers are stale: ${relative}`);
    } else fs.writeFileSync(target, content);
  }
}

export function inspectModules(root, manifest, preset = 'baseline') {
  if (!Object.hasOwn(manifest.modulePresets, preset)) throw new Error(`Unknown module preset ${preset}.`);
  const read = relative => {
    const absolute = path.resolve(root, relative);
    if (!absolute.startsWith(path.resolve(root) + path.sep)) throw new Error('Module path must stay in the repository.');
    return JSON.parse(fs.readFileSync(absolute, 'utf8'));
  };
  const configuration = read(manifest.modulePresets[preset]);
  if (!configuration.Modules || Object.keys(configuration).some(key => key !== 'Modules')) throw new Error('Invalid module preset.');
  const enabled = resolveModules(read(manifest.moduleCatalog), configuration.Modules);
  return { ModulesPreset: preset, Modules: enabled };
}
