<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="../TemplateV4.Infrastructure/TemplateV4.Infrastructure.csproj" />
  </ItemGroup>
</Project>
